var MONTH_NAMES=["January","February","March","April","May","June","July","August","September","October","November","December"],DOW=["S","M","T","W","T","F","S"],DAYS_IN_MONTH=[31,28,31,30,31,30,31,31,30,31,30,31],SHOW_MONTH="Click to display this month";function isLeapYear(a){a=a.getFullYear();if(a%4==0&&a%100!=0)return true;return a%400==0}function displayCurrentYear(a){a=a||(new Date).getFullYear();showYear(a)}
function getDaysInMonth(a){var b=DAYS_IN_MONTH[a.getMonth()];return b==28&&isLeapYear(a)?29:b}function getWeeksInMonth(a,b){var c=new Date(a,b,1),d=c.getDay();c=getDaysInMonth(c);return Math.ceil((d+c)/7)}
function getMonthHtml(a,b,c,d){var f=new Date,e=f.getFullYear(),g=f.getMonth();f=f.getDate();a.push('<table class="month" border=0 cellspacing=0>','<tr><td colspan=7 title="',SHOW_MONTH,'" class="monthHeader clickable" ','onclick="displayBirthdays(',b,",",c+1,')">',MONTH_NAMES[c],"<tr>");for(var k=0;k<DOW.length;++k)a.push('<td class="dow" style="color:black">',DOW[k]);k=new Date(b,c,1);var i=k.getDay(),m=getDaysInMonth(k),o=k=0;d=d||Math.ceil(m/7);for(i=1-i;;++i){var l=k++%7;if(d<=o&&l==0)break;
if(l==0){o>0&&a.push("</tr>");a.push("<tr>");++o}a.push('<td class="');var s="normal";if(b==e&&c==g&&i==f)s="today";if(i<=m&&(l==0||l==6))s="weekend ";a.push(s);if(i>=1&&i<=m)birthdayInfo[c+1]&&birthdayInfo[c+1][i]?a.push(' clickable" onclick="displayBirthdays(',b,",",c+1,",",i,')" title="',birthdayInfo[c+1][i].length,' friend(s)">',i):a.push('">',i);else a.push('">&nbsp;');a.push("</td>")}a.push("</tr></table>")}
function showYear(a){for(var b=["<table>"],c=0,d=0;d<12;++d){if(d%4==0){b.push("<tr>");c=Math.max(getWeeksInMonth(a,d),getWeeksInMonth(a,d+1),getWeeksInMonth(a,d+2),getWeeksInMonth(a,d+3))}b.push('<td class="outer">');getMonthHtml(b,a,d,c)}b.push("</table>");document.getElementById("calendar_div").innerHTML=b.join("")}var DARK_BLUE="#112aba",LIGHT_BLUE="#e8eef7",WEEKEND="#eee",WHITE="#fff",TODAY="#557799",TODAY_BORDER_DARK="#246",TODAY_BORDER_LIGHT="#9bd",BORDER_GREY="#a2bbd3",DIVIDER="#c3d9ff";
function getStyles(){var a=["<style>"];a.push(".month td {text-align: center; padding:2px 4px 1px}",".month,td.dow,td.monthHeader {background-color:",LIGHT_BLUE,"}","td.normal {background-color:",WHITE,"}","td.weekend {background-color:",WEEKEND,"}","td.outer {padding-right: 4px; padding-bottom: 4px; }","td.dow {border-width: 0 0 1px 0; border-style:solid;","border-color: ",DIVIDER,"}","td.today {padding: 1px 3px !important; background-color:",TODAY,";color:#fff !important; border-width: 1px; border-style:solid;",
"border-color: ",TODAY_BORDER_DARK," ",TODAY_BORDER_LIGHT," ",TODAY_BORDER_LIGHT," ",TODAY_BORDER_DARK,"}","td.monthHeader {font-weight:bold}",".month {background-color:",LIGHT_BLUE,";border: 1px solid ",BORDER_GREY,"}","body, td {font-family:Arial;font-size: 12.8px}","body {margin-left:10px; background-color:",WHITE,"}","td {vertical-align: top}",".clickable {font-weight:bold;cursor:pointer; color:",DARK_BLUE,"}",".clickable:hover {text-decoration: underline}");a.push("</style>");return a.join("")}
document.write(getStyles());function drawBirthdayTable(){var a=new google.visualization.DataTable;a.addColumn("number","Month");a.addColumn("number","Birthdays");a.addColumn("string","Friends");for(var b in birthdayInfo){var c=b;if(birthdayInfo.hasOwnProperty(b)){var d=birthdayInfo[b];if(b!="Unknown")b=MONTHS[b-1];var f="";total=0;for(var e in d)if(d.hasOwnProperty(e))for(var g=0;g<d[e].length;g++){f+=e=="Unknown"?friends[d[e][g]]+"<br>":"<b>"+e+"</b> - "+friends[d[e][g]]+"<br>";total++}b!="Unknown"&&a.addRow([{v:parseInt(c,
10),f:b},total,f])}}(new google.visualization.Table(document.getElementById("calendar_div_table"))).draw(a,{allowHtml:true})}
function drawLocationTable(){var a=new google.visualization.DataTable;a.addColumn("string","Location");a.addColumn("number","Count");a.addColumn("string","Friends");for(var b in locationInfo)if(locationInfo.hasOwnProperty(b)){for(var c=locationInfo[b],d=c.length,f="",e=0;e<c.length;e++)f+=e==0?friends[c[e]]:", "+friends[c[e]];b!="Unknown"&&a.addRow([b,d,f])}(new google.visualization.Table(document.getElementById("location_div_table"))).draw(a,{allowHtml:true})};var timeline,eventSource;
function createTimeline(){eventSource=new Timeline.DefaultEventSource;var a=document.getElementById("timeline_div"),b=Timeline.ClassicTheme.create();b.event.bubble.width=300;b.event.bubble.height=200;b.event.track.height=15;b.event.tape.height=8;b.timeline_start=new Date(Date.UTC(2005,10,1));b.timeline_stop=new Date(Date.UTC(2012,0,1));b=[Timeline.createBandInfo({width:"80%",intervalUnit:Timeline.DateTime.DAY,intervalPixels:500,eventSource:eventSource,theme:b,eventPainter:Timeline.CompactEventPainter,eventPainterParams:{iconWidth:25,
iconHeight:25,iconLabelGap:5,labelRightMargin:5,stackConcurrentPreciseInstantEvents:true},layout:"original"}),Timeline.createBandInfo({width:"10%",intervalUnit:Timeline.DateTime.MONTH,intervalPixels:200,eventSource:eventSource,theme:b,layout:"overview"}),Timeline.createBandInfo({width:"10%",intervalUnit:Timeline.DateTime.YEAR,intervalPixels:300,eventSource:eventSource,theme:b,layout:"overview"})];b[1].syncWith=0;b[1].highlight=true;b[2].syncWith=0;b[2].highlight=true;timeline=Timeline.create(a,b,
Timeline.HORIZONTAL);eventSource.loadJSON(timeline_data,".");timeline.layout()}var resizeTimerID=null;function onResize(){if(resizeTimerID==null)resizeTimerID=window.setTimeout(function(){resizeTimerID=null;timeline.layout()},500)}
function updateTimeline(a){timeline||createTimeline();var b=timeline_data;b.events=[];for(var c=0;c<a.length;c++){var d=a[c].postid,f=a[c].friendid,e=a[c].user,g=a[c].message,k=a[c].createdtime,i=k.getDateFromfacebookFormat().getTime(),m=timeline.timeline_start.getTime(),o=timeline.timeline_stop.getTime();if(i<m){m=new Date(i);m.setTime(m.getTime()+864E5);timeline.timeline_start=m}if(i>o){m=new Date(i);m.setTime(m.getTime()+864E5);timeline.timeline_stop=m}i=b.events.length;b.events[i]={};b.events[i].start=
k;b.events[i].description=g;b.events[i].textColor="#112aba";if(d!="")b.events[i].link="http://www.facebook.com/"+e+"/posts/"+d;b.events[i].image="http://graph.facebook.com/"+f+"/picture";b.events[i].icon="http://graph.facebook.com/"+f+"/picture"}eventSource.loadJSON(b,".")}function clearTimeline(){if(eventSource){eventSource.clear();timeline.layout()}}var timeline_data={dateTimeFormat:"iso8601",events:[]};
Timeline.DefaultEventSource.Event.prototype.fillInfoBubble=function(a,b,c){var d=a.ownerDocument,f=this.getLink(),e=this.getImage();if(e!=null){var g=d.createElement("img");g.src=e;b.event.bubble.imageStyler(g);a.appendChild(g)}e=d.createElement("div");g=d.createTextNode("View post on Facebook");if(f!=null){var k=d.createElement("a");k.href=f;k.setAttribute("target","new");k.appendChild(g);e.appendChild(k)}else e.appendChild(g);b.event.bubble.titleStyler(e);a.appendChild(e);f=d.createElement("div");
this.fillDescription(f);b.event.bubble.bodyStyler(f);a.appendChild(f);a.appendChild(d.createElement("br"));d=d.createElement("div");this.fillTime(d,c);b.event.bubble.timeStyler(d);a.appendChild(d)};Timeline.CompactEventPainter=function(a){this._params=a;this._onSelectListeners=[];this._frc=this._highlightMatcher=this._filterMatcher=null;this._eventIdToElmt={}};Timeline.CompactEventPainter.prototype.initialize=function(a,b){this._band=a;this._timeline=b;this._eventIdToElmt=this._highlightLayer=this._lineLayer=this._eventLayer=this._backLayer=null};Timeline.CompactEventPainter.prototype.addOnSelectListener=function(a){this._onSelectListeners.push(a)};
Timeline.CompactEventPainter.prototype.removeOnSelectListener=function(a){for(var b=0;b<this._onSelectListeners.length;b++)if(this._onSelectListeners[b]==a){this._onSelectListeners.splice(b,1);break}};Timeline.CompactEventPainter.prototype.getFilterMatcher=function(){return this._filterMatcher};Timeline.CompactEventPainter.prototype.setFilterMatcher=function(a){this._filterMatcher=a};Timeline.CompactEventPainter.prototype.getHighlightMatcher=function(){return this._highlightMatcher};
Timeline.CompactEventPainter.prototype.setHighlightMatcher=function(a){this._highlightMatcher=a};
Timeline.CompactEventPainter.prototype.paint=function(){var a=this._band.getEventSource();if(a!=null){this._eventIdToElmt={};this._prepareForPainting();var b=this._params.theme,c=b.event;b={trackOffset:"trackOffset"in this._params?this._params.trackOffset:10,trackHeight:"trackHeight"in this._params?this._params.trackHeight:10,tapeHeight:b.event.tape.height,tapeBottomMargin:"tapeBottomMargin"in this._params?this._params.tapeBottomMargin:2,labelBottomMargin:"labelBottomMargin"in this._params?this._params.labelBottomMargin:
5,labelRightMargin:"labelRightMargin"in this._params?this._params.labelRightMargin:5,defaultIcon:c.instant.icon,defaultIconWidth:c.instant.iconWidth,defaultIconHeight:c.instant.iconHeight,customIconWidth:"iconWidth"in this._params?this._params.iconWidth:c.instant.iconWidth,customIconHeight:"iconHeight"in this._params?this._params.iconHeight:c.instant.iconHeight,iconLabelGap:"iconLabelGap"in this._params?this._params.iconLabelGap:2,iconBottomMargin:"iconBottomMargin"in this._params?this._params.iconBottomMargin:
2};if("compositeIcon"in this._params){b.compositeIcon=this._params.compositeIcon;b.compositeIconWidth=this._params.compositeIconWidth||b.customIconWidth;b.compositeIconHeight=this._params.compositeIconHeight||b.customIconHeight}else{b.compositeIcon=b.defaultIcon;b.compositeIconWidth=b.defaultIconWidth;b.compositeIconHeight=b.defaultIconHeight}var d=this._band.getMinDate(),f=this._band.getMaxDate(),e=this._filterMatcher!=null?this._filterMatcher:function(){return true};c=this._highlightMatcher!=null?
this._highlightMatcher:function(){return-1};f=a.getEventIterator(d,f);a="stackConcurrentPreciseInstantEvents"in this._params&&this._params.stackConcurrentPreciseInstantEvents;if("collapseConcurrentPreciseInstantEvents"in this._params&&this._params.collapseConcurrentPreciseInstantEvents||a){d=[];for(var g=null;f.hasNext();){var k=f.next();if(e(k))if(!k.isInstant()||k.isImprecise())this.paintEvent(k,b,this._params.theme,c(k));else if(g!=null&&g.getStart().getTime()==k.getStart().getTime())d[d.length-
1].push(k);else{d.push([k]);g=k}}for(e=0;e<d.length;e++){f=d[e];if(f.length==1)this.paintEvent(f[0],b,this._params.theme,c(k));else{g=-1;for(var i=0;g<0&&i<f.length;i++)g=c(f[i]);a?this.paintStackedPreciseInstantEvents(f,b,this._params.theme,g):this.paintCompositePreciseInstantEvents(f,b,this._params.theme,g)}}}else for(;f.hasNext();){k=f.next();e(k)&&this.paintEvent(k,b,this._params.theme,c(k))}this._highlightLayer.style.display="block";this._lineLayer.style.display="block";this._eventLayer.style.display=
"block"}};Timeline.CompactEventPainter.prototype.softPaint=function(){};
Timeline.CompactEventPainter.prototype._prepareForPainting=function(){var a=this._band;if(this._backLayer==null){this._backLayer=this._band.createLayerDiv(0,"timeline-band-events");this._backLayer.style.visibility="hidden";var b=document.createElement("span");b.className="timeline-event-label";this._backLayer.appendChild(b);this._frc=SimileAjax.Graphics.getFontRenderingContext(b)}this._frc.update();this._tracks=[];this._highlightLayer!=null&&a.removeLayerDiv(this._highlightLayer);this._highlightLayer=
a.createLayerDiv(105,"timeline-band-highlights");this._highlightLayer.style.display="none";this._lineLayer!=null&&a.removeLayerDiv(this._lineLayer);this._lineLayer=a.createLayerDiv(110,"timeline-band-lines");this._lineLayer.style.display="none";this._eventLayer!=null&&a.removeLayerDiv(this._eventLayer);this._eventLayer=a.createLayerDiv(115,"timeline-band-events");this._eventLayer.style.display="none"};
Timeline.CompactEventPainter.prototype.paintEvent=function(a,b,c,d){a.isInstant()?this.paintInstantEvent(a,b,c,d):this.paintDurationEvent(a,b,c,d)};Timeline.CompactEventPainter.prototype.paintInstantEvent=function(a,b,c,d){a.isImprecise()?this.paintImpreciseInstantEvent(a,b,c,d):this.paintPreciseInstantEvent(a,b,c,d)};Timeline.CompactEventPainter.prototype.paintDurationEvent=function(a,b,c,d){a.isImprecise()?this.paintImpreciseDurationEvent(a,b,c,d):this.paintPreciseDurationEvent(a,b,c,d)};
Timeline.CompactEventPainter.prototype.paintPreciseInstantEvent=function(a,b,c,d){var f={tooltip:a.getProperty("tooltip")||a.getText()},e={url:a.getIcon()};if(e.url==null){e.url=b.defaultIcon;e.width=b.defaultIconWidth;e.height=b.defaultIconHeight}else{e.width=a.getProperty("iconWidth")||b.customIconWidth;e.height=a.getProperty("iconHeight")||b.customIconHeight}var g={text:a.getText(),color:a.getTextColor()||a.getColor(),className:a.getClassName()},k=this.paintTapeIconLabel(a.getStart(),f,null,e,
g,b,c,d),i=this;b=function(m,o){return i._onClickInstantEvent(k.iconElmtData.elmt,o,a)};SimileAjax.DOM.registerEvent(k.iconElmtData.elmt,"mousedown",b);SimileAjax.DOM.registerEvent(k.labelElmtData.elmt,"mousedown",b);this._eventIdToElmt[a.getID()]=k.iconElmtData.elmt};
Timeline.CompactEventPainter.prototype.paintCompositePreciseInstantEvents=function(a,b,c,d){for(var f=a[0],e=[],g=0;g<a.length;g++)e.push(a[g].getProperty("tooltip")||a[g].getText());e={tooltip:e.join("; ")};g={url:b.compositeIcon,width:b.compositeIconWidth,height:b.compositeIconHeight};var k={text:String.substitute(this._params.compositeEventLabelTemplate,[a.length])},i=this.paintTapeIconLabel(f.getStart(),e,null,g,k,b,c,d),m=this;b=function(o,l){return m._onClickCompositePreciseInstantEvent(i.iconElmtData.elmt,
l,a)};SimileAjax.DOM.registerEvent(i.iconElmtData.elmt,"mousedown",b);SimileAjax.DOM.registerEvent(i.labelElmtData.elmt,"mousedown",b);for(g=0;g<a.length;g++)this._eventIdToElmt[a[g].getID()]=i.iconElmtData.elmt};
Timeline.CompactEventPainter.prototype.paintStackedPreciseInstantEvents=function(a,b,c){for(var d=this._band,f=function(y){var t={url:y.getIcon()};if(t.url==null){t.url=b.defaultIcon;t.width=b.defaultIconWidth;t.height=b.defaultIconHeight}else{t.width=y.getProperty("iconWidth")||b.customIconWidth;t.height=y.getProperty("iconHeight")||b.customIconHeight}return t},e=f(a[0]),g=0,k=0,i=0,m=0,o=[],l=0;l<a.length;l++){var s=a[l],v=s.getText();s=f(s);var F=this._frc.computeSize(v);v={text:v,iconData:s,labelSize:F,
iconLeft:e.width+l*15-s.width};v.labelLeft=e.width+l*15+b.iconLabelGap;v.top=l*15;o.push(v);g=Math.min(g,v.iconLeft);i+=F.height;k=Math.max(k,v.labelLeft+F.width);m=Math.max(m,v.top+s.height)}k+=b.labelRightMargin;i+=b.labelBottomMargin;m+=b.iconBottomMargin;var A=function(y){return Math.round(d.dateToPixelOffset(y))}(a[0].getStart());f=[];v=Math.ceil(Math.max(m,i)/b.trackHeight);e=e.width+(a.length-1)*15;for(l=0;l<v;l++)f.push({start:g,end:e});g=Math.ceil(i/b.trackHeight);for(l=0;l<g;l++){i=f[l];
i.end=Math.max(i.end,k)}var J=this._fitTracks(A,f)*b.trackHeight+b.trackOffset,u=this._timeline.getDocument().createElement("div");u.className="timeline-event-icon-stack";u.style.position="absolute";u.style.overflow="visible";u.style.left=A+"px";u.style.top=J+"px";u.style.width=e+25+"px";u.style.height=m+25+"px";u.innerHTML="<div style='position: relative'></div>";u.onmouseout=function(y){y.cancelBubble=true;y.stopPropagation&&y.stopPropagation();try{var t=u.firstChild.childNodes;for(y=0;y<t.length;y++)t[y].style.zIndex=
t.length-y}catch(r){}};this._eventLayer.appendChild(u);var G=this,M=function(){try{for(var y=parseInt(this.getAttribute("index")),t=u.firstChild.childNodes,r=0;r<t.length;r++)t[r].style.zIndex=r==y?t.length:t.length-r}catch(D){}};k=function(y){var t=o[y],r=a[y],D=r.getProperty("tooltip")||r.getText(),K=G._paintEventLabel({tooltip:D},{text:t.text},A+t.labelLeft,J+t.top,t.labelSize.width,t.labelSize.height,c);K.elmt.setAttribute("index",y);K.elmt.onmouseover=M;var I=SimileAjax.Graphics.createTranslucentImage(t.iconData.url);
D=G._timeline.getDocument().createElement("div");D.className="timeline-event-icon";D.style.left=t.iconLeft+"px";D.style.top=t.top+"px";D.style.zIndex=o.length-y;D.appendChild(I);D.setAttribute("index",y);D.onmouseover=M;u.firstChild.appendChild(D);y=function(R,L){return G._onClickInstantEvent(K.elmt,L,r)};SimileAjax.DOM.registerEvent(D,"mousedown",y);SimileAjax.DOM.registerEvent(K.elmt,"mousedown",y);G._eventIdToElmt[r.getID()]=D};for(l=0;l<o.length;l++)k(l)};
Timeline.CompactEventPainter.prototype.paintImpreciseInstantEvent=function(a,b,c,d){var f={tooltip:a.getProperty("tooltip")||a.getText()},e={start:a.getStart(),end:a.getEnd(),latestStart:a.getLatestStart(),earliestEnd:a.getEarliestEnd(),isInstant:true},g={url:a.getIcon()};if(g.url==null)g=null;else{g.width=a.getProperty("iconWidth")||b.customIconWidth;g.height=a.getProperty("iconHeight")||b.customIconHeight}var k={text:a.getText(),color:a.getTextColor()||a.getColor(),className:a.getClassName()},i=
this.paintTapeIconLabel(a.getStart(),f,e,g,k,b,c,d),m=this;b=g!=null?function(o,l){return m._onClickInstantEvent(i.iconElmtData.elmt,l,a)}:function(o,l){return m._onClickInstantEvent(i.labelElmtData.elmt,l,a)};SimileAjax.DOM.registerEvent(i.labelElmtData.elmt,"mousedown",b);SimileAjax.DOM.registerEvent(i.impreciseTapeElmtData.elmt,"mousedown",b);if(g!=null){SimileAjax.DOM.registerEvent(i.iconElmtData.elmt,"mousedown",b);this._eventIdToElmt[a.getID()]=i.iconElmtData.elmt}else this._eventIdToElmt[a.getID()]=
i.labelElmtData.elmt};
Timeline.CompactEventPainter.prototype.paintPreciseDurationEvent=function(a,b,c,d){var f={tooltip:a.getProperty("tooltip")||a.getText()},e={start:a.getStart(),end:a.getEnd(),isInstant:false},g={url:a.getIcon()};if(g.url==null)g=null;else{g.width=a.getProperty("iconWidth")||b.customIconWidth;g.height=a.getProperty("iconHeight")||b.customIconHeight}var k={text:a.getText(),color:a.getTextColor()||a.getColor(),className:a.getClassName()},i=this.paintTapeIconLabel(a.getLatestStart(),f,e,g,k,b,c,d),m=this;
b=g!=null?function(o,l){return m._onClickInstantEvent(i.iconElmtData.elmt,l,a)}:function(o,l){return m._onClickInstantEvent(i.labelElmtData.elmt,l,a)};SimileAjax.DOM.registerEvent(i.labelElmtData.elmt,"mousedown",b);SimileAjax.DOM.registerEvent(i.tapeElmtData.elmt,"mousedown",b);if(g!=null){SimileAjax.DOM.registerEvent(i.iconElmtData.elmt,"mousedown",b);this._eventIdToElmt[a.getID()]=i.iconElmtData.elmt}else this._eventIdToElmt[a.getID()]=i.labelElmtData.elmt};
Timeline.CompactEventPainter.prototype.paintImpreciseDurationEvent=function(a,b,c,d){var f={tooltip:a.getProperty("tooltip")||a.getText()},e={start:a.getStart(),end:a.getEnd(),latestStart:a.getLatestStart(),earliestEnd:a.getEarliestEnd(),isInstant:false},g={url:a.getIcon()};if(g.url==null)g=null;else{g.width=a.getProperty("iconWidth")||b.customIconWidth;g.height=a.getProperty("iconHeight")||b.customIconHeight}var k={text:a.getText(),color:a.getTextColor()||a.getColor(),className:a.getClassName()},
i=this.paintTapeIconLabel(a.getLatestStart(),f,e,g,k,b,c,d),m=this;b=g!=null?function(o,l){return m._onClickInstantEvent(i.iconElmtData.elmt,l,a)}:function(o,l){return m._onClickInstantEvent(i.labelElmtData.elmt,l,a)};SimileAjax.DOM.registerEvent(i.labelElmtData.elmt,"mousedown",b);SimileAjax.DOM.registerEvent(i.tapeElmtData.elmt,"mousedown",b);if(g!=null){SimileAjax.DOM.registerEvent(i.iconElmtData.elmt,"mousedown",b);this._eventIdToElmt[a.getID()]=i.iconElmtData.elmt}else this._eventIdToElmt[a.getID()]=
i.labelElmtData.elmt};
Timeline.CompactEventPainter.prototype.paintTapeIconLabel=function(a,b,c,d,f,e,g){var k=this._band,i=function(G){return Math.round(k.dateToPixelOffset(G))};a=i(a);var m=[],o=0,l=0,s=0;if(c!=null){o=e.tapeHeight+e.tapeBottomMargin;l=Math.ceil(e.tapeHeight/e.trackHeight);for(var v=i(c.end)-a,F=i(c.start)-a,A=0;A<l;A++)m.push({start:F,end:v});s=e.trackHeight-o%e.tapeHeight}F=v=0;if(d!=null){if("iconAlign"in d&&d.iconAlign=="center")v=-Math.floor(d.width/2);F=v+d.width+e.iconLabelGap;if(l>0)m[l-1].end=
Math.max(m[l-1].end,F);for(A=d.height+e.iconBottomMargin+s;A>0;){m.push({start:v,end:F});A-=e.trackHeight}}A=this._frc.computeSize(f.text);s=A.height+e.labelBottomMargin+s;var J=F+A.width+e.labelRightMargin;if(l>0)m[l-1].end=Math.max(m[l-1].end,J);for(var u=0;s>0;u++){if(l+u<m.length)m[l+u].end=J;else m.push({start:0,end:J});s-=e.trackHeight}m=this._fitTracks(a,m)*e.trackHeight+e.trackOffset;l={};l.labelElmtData=this._paintEventLabel(b,f,a+F,m+o,A.width,A.height,g);if(c!=null){if("latestStart"in c||
"earliestEnd"in c)l.impreciseTapeElmtData=this._paintEventTape(b,c,e.tapeHeight,m,i(c.start),i(c.end),g.event.duration.impreciseColor,g.event.duration.impreciseOpacity,e,g);if(!c.isInstant&&"start"in c&&"end"in c)l.tapeElmtData=this._paintEventTape(b,c,e.tapeHeight,m,a,i("earliestEnd"in c?c.earliestEnd:c.end),c.color,100,e,g)}if(d!=null)l.iconElmtData=this._paintEventIcon(b,d,m+o,a+v,e,g);return l};
Timeline.CompactEventPainter.prototype._fitTracks=function(a,b){var c;for(c=0;c<this._tracks.length;c++){for(var d=true,f=0;f<b.length&&c+f<this._tracks.length;f++)if(a+b[f].start<this._tracks[c+f]){d=false;break}if(d)break}for(d=0;d<b.length;d++)this._tracks[c+d]=a+b[d].end;return c};
Timeline.CompactEventPainter.prototype._paintEventIcon=function(a,b,c,d,f){b=SimileAjax.Graphics.createTranslucentImage(b.url);var e=this._timeline.getDocument().createElement("div");e.className="timeline-event-icon";e.style.left=d+"px";e.style.top=c+"px";e.appendChild(b);if("tooltip"in a&&typeof a.tooltip=="string")e.title=a.tooltip;this._eventLayer.appendChild(e);return{left:d,top:c,width:f.iconWidth,height:f.iconHeight,elmt:e}};
Timeline.CompactEventPainter.prototype._paintEventLabel=function(a,b,c,d,f,e){var g=this._timeline.getDocument().createElement("div");g.className="timeline-event-label tinytext";g.style.left=c+"px";g.style.width=f+1+"px";g.style.top=d+"px";g.innerHTML=b.text;if("tooltip"in a&&typeof a.tooltip=="string")g.title=a.tooltip;if("color"in b&&typeof b.color=="string")g.style.color=b.color;if("className"in b&&typeof b.className=="string")g.className+=" "+b.className;this._eventLayer.appendChild(g);return{left:c,
top:d,width:f,height:e,elmt:g}};
Timeline.CompactEventPainter.prototype._paintEventTape=function(a,b,c,d,f,e,g,k){e-=f;var i=this._timeline.getDocument().createElement("div");i.className="timeline-event-tape";i.style.left=f+"px";i.style.top=d+"px";i.style.width=e+"px";i.style.height=c+"px";if("tooltip"in a&&typeof a.tooltip=="string")i.title=a.tooltip;if(g!=null&&typeof b.color=="string")i.style.backgroundColor=g;if("backgroundImage"in b&&typeof b.backgroundImage=="string"){i.style.backgroundImage="url("+backgroundImage+")";i.style.backgroundRepeat=
"backgroundRepeat"in b&&typeof b.backgroundRepeat=="string"?b.backgroundRepeat:"repeat"}SimileAjax.Graphics.setOpacity(i,k);if("className"in b&&typeof b.className=="string")i.className+=" "+b.className;this._eventLayer.appendChild(i);return{left:f,top:d,width:e,height:c,elmt:i}};
Timeline.CompactEventPainter.prototype._createHighlightDiv=function(a,b){if(a>=0){var c=this._timeline.getDocument().createElement("div");c.style.position="absolute";c.style.overflow="hidden";c.style.left=b.left-2+"px";c.style.width=b.width+4+"px";c.style.top=b.top-2+"px";c.style.height=b.height+4+"px";this._highlightLayer.appendChild(c)}};
Timeline.CompactEventPainter.prototype._onClickCompositePreciseInstantEvent=function(a,b,c){var d=SimileAjax.DOM.getPageCoordinates(a);this._showBubble(d.left+Math.ceil(a.offsetWidth/2),d.top+Math.ceil(a.offsetHeight/2),c);a=[];for(d=0;d<c.length;d++)a.push(c[d].getID());this._fireOnSelect(a);b.cancelBubble=true;SimileAjax.DOM.cancelEvent(b);return false};
Timeline.CompactEventPainter.prototype._onClickInstantEvent=function(a,b,c){var d=SimileAjax.DOM.getPageCoordinates(a);this._showBubble(d.left+Math.ceil(a.offsetWidth/2),d.top+Math.ceil(a.offsetHeight/2),[c]);this._fireOnSelect([c.getID()]);b.cancelBubble=true;SimileAjax.DOM.cancelEvent(b);return false};
Timeline.CompactEventPainter.prototype._onClickDurationEvent=function(a,b,c){if("pageX"in b){a=b.pageX;var d=b.pageY}else{d=SimileAjax.DOM.getPageCoordinates(a);a=b.offsetX+d.left;d=b.offsetY+d.top}this._showBubble(a,d,[c]);this._fireOnSelect([c.getID()]);b.cancelBubble=true;SimileAjax.DOM.cancelEvent(b);return false};
Timeline.CompactEventPainter.prototype.showBubble=function(a){var b=this._eventIdToElmt[a.getID()];if(b){var c=SimileAjax.DOM.getPageCoordinates(b);this._showBubble(c.left+b.offsetWidth/2,c.top+b.offsetHeight/2,[a])}};
Timeline.CompactEventPainter.prototype._showBubble=function(a,b,c){var d=document.createElement("div");c="fillInfoBubble"in c?[c]:c;for(var f=0;f<c.length;f++){var e=document.createElement("div");d.appendChild(e);c[f].fillInfoBubble(e,this._params.theme,this._band.getLabeller())}SimileAjax.WindowManager.cancelPopups();SimileAjax.Graphics.createBubbleForContentAndPoint(d,a,b,this._params.theme.event.bubble.width)};Timeline.CompactEventPainter.prototype._fireOnSelect=function(a){for(var b=0;b<this._onSelectListeners.length;b++)this._onSelectListeners[b](a)};function UProgressBar(a){this.elid=a.elid;this.id="upb"+Math.ceil(Math.random()*1E8);this.created=false;this.minValue=a.min?a.min:0;this.maxValue=a.max?a.max:0;this.value=a.value?a.value:0}UProgressBar.prototype.setValue=function(a){log("setting value to "+a+" MaxValue is "+this.maxValue);this.value=a;this.paint();this.value==this.maxValue&&this.hide()};
UProgressBar.prototype.paint=function(){log("painting");if(!this.created){var a=document.createElement("div");a.setAttribute("class","progressbar");a.setAttribute("id",this.id+"progressbar");var b=document.createElement("div");b.setAttribute("class","progress");b.setAttribute("id",this.id+"progress");a.appendChild(b);document.getElementById(this.elid).appendChild(a);this.created=true}a=[100*this.value/(this.maxValue-this.minValue)]*2;document.getElementById(this.id+"progress").style.width=a+"px";
log("new width = "+a+"px")};UProgressBar.prototype.getMinValue=function(){return this.minVale};UProgressBar.prototype.getMaxValue=function(){return this.maxValue};UProgressBar.prototype.setMaxValue=function(a){this.maxValue=a};UProgressBar.prototype.getCurrentValue=function(){return this.value};UProgressBar.prototype.hide=function(){log("hiding");document.getElementById(this.id+"progressbar").style.display="none";document.getElementById(this.id+"progress").style.width="0px"};
UProgressBar.prototype.initialize=function(){document.getElementById(this.id+"progressbar").style.display="";document.getElementById(this.id+"progress").style.width="0px";this.value=this.minValue};var gviz_word_cumulus={};gviz_word_cumulus.WordCumulus=function(a){this.container_=a};
gviz_word_cumulus.WordCumulus.prototype.draw=function(a,b){this.data_=a;b=b||{};var c={};c.allowScriptAccess="always";c.wmode="transparent";c.id=this.container_.id;for(var d={mode:"tags",distr:"false",tcolor:(b.text_color||"#ff0000").replace("#","0x"),hcolor:(b.hover_text_color||"#000000").replace("#","0x"),speed:b.speed||100},f="<tags>",e=0;e<a.getNumberOfRows();e++){var g=a.getFormattedValue(e,0),k=a.getFormattedValue(e,1);k="123456";var i=4;if(a.getNumberOfColumns()>2)i=a.getFormattedValue(e,2);
f+="<a href='"+k+"' target='_blank' style='font-size:"+String(i)+"pt;'>"+g+"</a>"}f+="</tags>";d.tagcloud=f;swfobject.embedSWF("http://word-cumulus-goog-vis.googlecode.com/svn/trunk/tagcloud.swf",this.container_.id,b.width||400,b.height||300,"10","",d,{},c)};var swfobject=function(){function a(){if(S.readyState=="complete"){S.parentNode.removeChild(S);b()}}function b(){if(!U){if(q.ie&&q.win){var h=r.createElement("span");try{var j=r.getElementsByTagName("body")[0].appendChild(h);j.parentNode.removeChild(j)}catch(n){return}}U=true;if(V){clearInterval(V);V=null}h=K.length;for(j=0;j<h;j++)K[j]()}}function c(h){if(U)h();else K[K.length]=h}function d(h){if(typeof t.addEventListener!=u)t.addEventListener("load",h,false);else if(typeof r.addEventListener!=u)r.addEventListener("load",
h,false);else if(typeof t.attachEvent!=u)s(t,"onload",h);else if(typeof t.onload=="function"){var j=t.onload;t.onload=function(){j();h()}}else t.onload=h}function f(){for(var h=I.length,j=0;j<h;j++){var n=I[j].id;if(q.pv[0]>0){var p=l(n);if(p){I[j].width=p.getAttribute("width")?p.getAttribute("width"):"0";I[j].height=p.getAttribute("height")?p.getAttribute("height"):"0";if(v(I[j].swfVersion)){if(q.webkit&&q.webkit<312){var w=p.getElementsByTagName(G)[0];if(w){var B=r.createElement("embed"),x=w.attributes;
if(x)for(var z=x.length,C=0;C<z;C++)x[C].nodeName=="DATA"?B.setAttribute("src",x[C].nodeValue):B.setAttribute(x[C].nodeName,x[C].nodeValue);if(w=w.childNodes){x=w.length;for(z=0;z<x;z++)w[z].nodeType==1&&w[z].nodeName=="PARAM"&&B.setAttribute(w[z].getAttribute("name"),w[z].getAttribute("value"))}p.parentNode.replaceChild(B,p)}}A(n,true)}else I[j].expressInstall&&!N&&v("6.0.65")&&(q.win||q.mac)?e(I[j]):g(p)}}else A(n,true)}}function e(h){N=true;var j=l(h.id);if(j){if(h.altContentId){var n=l(h.altContentId);
if(n){O=n;W=h.altContentId}}else O=k(j);if(!/%$/.test(h.width)&&parseInt(h.width,10)<310)h.width="310";if(!/%$/.test(h.height)&&parseInt(h.height,10)<137)h.height="137";r.title=r.title.slice(0,47)+" - Flash Player Installation";n="MMredirectURL="+t.location+"&MMplayerType="+(q.ie&&q.win?"ActiveX":"PlugIn")+"&MMdoctitle="+r.title;var p=h.id;if(q.ie&&q.win&&j.readyState!=4){var w=r.createElement("div");p+="SWFObjectNew";w.setAttribute("id",p);j.parentNode.insertBefore(w,j);j.style.display="none";s(t,
"onload",function(){j.parentNode.removeChild(j)})}i({data:h.expressInstall,id:y,width:h.width,height:h.height},{flashvars:n},p)}}function g(h){if(q.ie&&q.win&&h.readyState!=4){var j=r.createElement("div");h.parentNode.insertBefore(j,h);j.parentNode.replaceChild(k(h),j);h.style.display="none";s(t,"onload",function(){h.parentNode.removeChild(h)})}else h.parentNode.replaceChild(k(h),h)}function k(h){var j=r.createElement("div");if(q.win&&q.ie)j.innerHTML=h.innerHTML;else if(h=h.getElementsByTagName(G)[0])if(h=
h.childNodes)for(var n=h.length,p=0;p<n;p++)!(h[p].nodeType==1&&h[p].nodeName=="PARAM")&&h[p].nodeType!=8&&j.appendChild(h[p].cloneNode(true));return j}function i(h,j,n){var p,w=l(n);if(w){if(typeof h.id==u)h.id=n;if(q.ie&&q.win){var B="",x;for(x in h)if(h[x]!=Object.prototype[x])if(x.toLowerCase()=="data")j.movie=h[x];else if(x.toLowerCase()=="styleclass")B+=' class="'+h[x]+'"';else if(x.toLowerCase()!="classid")B+=" "+x+'="'+h[x]+'"';x="";for(var z in j)if(j[z]!=Object.prototype[z])x+='<param name="'+
z+'" value="'+j[z]+'" />';w.outerHTML='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+B+">"+x+"</object>";R[R.length]=h.id;p=l(h.id)}else if(q.webkit&&q.webkit<312){B=r.createElement("embed");B.setAttribute("type",M);for(var C in h)if(h[C]!=Object.prototype[C])if(C.toLowerCase()=="data")B.setAttribute("src",h[C]);else if(C.toLowerCase()=="styleclass")B.setAttribute("class",h[C]);else C.toLowerCase()!="classid"&&B.setAttribute(C,h[C]);for(var E in j)j[E]!=Object.prototype[E]&&E.toLowerCase()!=
"movie"&&B.setAttribute(E,j[E]);w.parentNode.replaceChild(B,w);p=B}else{z=r.createElement(G);z.setAttribute("type",M);for(var H in h)if(h[H]!=Object.prototype[H])if(H.toLowerCase()=="styleclass")z.setAttribute("class",h[H]);else H.toLowerCase()!="classid"&&z.setAttribute(H,h[H]);for(B in j)if(j[B]!=Object.prototype[B]&&B.toLowerCase()!="movie"){h=z;x=B;C=j[B];E=r.createElement("param");E.setAttribute("name",x);E.setAttribute("value",C);h.appendChild(E)}w.parentNode.replaceChild(z,w);p=z}}return p}
function m(h){var j=l(h);if(j&&(j.nodeName=="OBJECT"||j.nodeName=="EMBED"))if(q.ie&&q.win)j.readyState==4?o(h):t.attachEvent("onload",function(){o(h)});else j.parentNode.removeChild(j)}function o(h){if(h=l(h)){for(var j in h)if(typeof h[j]=="function")h[j]=null;h.parentNode.removeChild(h)}}function l(h){var j=null;try{j=r.getElementById(h)}catch(n){}return j}function s(h,j,n){h.attachEvent(j,n);L[L.length]=[h,j,n]}function v(h){var j=q.pv;h=h.split(".");h[0]=parseInt(h[0],10);h[1]=parseInt(h[1],10)||
0;h[2]=parseInt(h[2],10)||0;return j[0]>h[0]||j[0]==h[0]&&j[1]>h[1]||j[0]==h[0]&&j[1]==h[1]&&j[2]>=h[2]?true:false}function F(h,j){if(!(q.ie&&q.mac)){var n=r.getElementsByTagName("head")[0],p=r.createElement("style");p.setAttribute("type","text/css");p.setAttribute("media","screen");!(q.ie&&q.win)&&typeof r.createTextNode!=u&&p.appendChild(r.createTextNode(h+" {"+j+"}"));n.appendChild(p);if(q.ie&&q.win&&typeof r.styleSheets!=u&&r.styleSheets.length>0){n=r.styleSheets[r.styleSheets.length-1];typeof n.addRule==
G&&n.addRule(h,j)}}}function A(h,j){var n=j?"visible":"hidden";if(U&&l(h))l(h).style.visibility=n;else F("#"+h,"visibility:"+n)}function J(h){return/[\\\"<>\.;]/.exec(h)!=null?encodeURIComponent(h):h}var u="undefined",G="object",M="application/x-shockwave-flash",y="SWFObjectExprInst",t=window,r=document,D=navigator,K=[],I=[],R=[],L=[],S,V=null,O=null,W=null,U=false,N=false,q=function(){var h=typeof r.getElementById!=u&&typeof r.getElementsByTagName!=u&&typeof r.createElement!=u,j=[0,0,0],n=null;if(typeof D.plugins!=
u&&typeof D.plugins["Shockwave Flash"]==G){if((n=D.plugins["Shockwave Flash"].description)&&!(typeof D.mimeTypes!=u&&D.mimeTypes[M]&&!D.mimeTypes[M].enabledPlugin)){n=n.replace(/^.*\s+(\S+\s+\S+$)/,"$1");j[0]=parseInt(n.replace(/^(.*)\..*$/,"$1"),10);j[1]=parseInt(n.replace(/^.*\.(.*)\s.*$/,"$1"),10);j[2]=/r/.test(n)?parseInt(n.replace(/^.*r(.*)$/,"$1"),10):0}}else if(typeof t.ActiveXObject!=u){var p=null,w=false;try{p=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(B){try{p=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");
j=[6,0,21];p.AllowScriptAccess="always"}catch(x){if(j[0]==6)w=true}if(!w)try{p=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(z){}}if(!w&&p)try{if(n=p.GetVariable("$version")){n=n.split(" ")[1].split(",");j=[parseInt(n[0],10),parseInt(n[1],10),parseInt(n[2],10)]}}catch(C){}}w=D.userAgent.toLowerCase();var E=D.platform.toLowerCase();n=/webkit/.test(w)?parseFloat(w.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):false;p=E?/win/.test(E):/win/.test(w);w=E?/mac/.test(E):/mac/.test(w);return{w3cdom:h,
pv:j,webkit:n,ie:false,win:p,mac:w}}();(function(){if(q.w3cdom){c(f);if(q.ie&&q.win)try{r.write("<script id=__ie_ondomload defer=true src=//:><\/script>");(S=l("__ie_ondomload"))&&s(S,"onreadystatechange",a)}catch(h){}if(q.webkit&&typeof r.readyState!=u)V=setInterval(function(){/loaded|complete/.test(r.readyState)&&b()},10);typeof r.addEventListener!=u&&r.addEventListener("DOMContentLoaded",b,null);d(b)}})();(function(){q.ie&&q.win&&window.attachEvent("onunload",function(){for(var h=L.length,j=0;j<
h;j++)L[j][0].detachEvent(L[j][1],L[j][2]);h=R.length;for(j=0;j<h;j++)m(R[j]);for(var n in q)q[n]=null;q=null;for(var p in swfobject)swfobject[p]=null;swfobject=null})})();return{registerObject:function(h,j,n){if(!(!q.w3cdom||!h||!j)){var p={};p.id=h;p.swfVersion=j;p.expressInstall=n?n:false;I[I.length]=p;A(h,false)}},getObjectById:function(h){var j=null;if(q.w3cdom)if(h=l(h)){var n=h.getElementsByTagName(G)[0];if(!n||n&&typeof h.SetVariable!=u)j=h;else if(typeof n.SetVariable!=u)j=n}return j},embedSWF:function(h,
j,n,p,w,B,x,z,C){if(!(!q.w3cdom||!h||!j||!n||!p||!w)){n+="";p+="";if(v(w)){A(j,false);var E={};if(C&&typeof C===G)for(var H in C)if(C[H]!=Object.prototype[H])E[H]=C[H];E.data=h;E.width=n;E.height=p;var T={};if(z&&typeof z===G)for(var X in z)if(z[X]!=Object.prototype[X])T[X]=z[X];if(x&&typeof x===G)for(var P in x)if(x[P]!=Object.prototype[P])if(typeof T.flashvars!=u)T.flashvars+="&"+P+"="+x[P];else T.flashvars=P+"="+x[P];c(function(){i(E,T,j);E.id==j&&A(j,true)})}else if(B&&!N&&v("6.0.65")&&(q.win||
q.mac)){N=true;A(j,false);c(function(){var Q={};Q.id=Q.altContentId=j;Q.width=n;Q.height=p;Q.expressInstall=B;e(Q)})}}},getFlashPlayerVersion:function(){return{major:q.pv[0],minor:q.pv[1],release:q.pv[2]}},hasFlashPlayerVersion:v,createSWF:function(h,j,n){if(q.w3cdom)return i(h,j,n)},removeSWF:function(h){q.w3cdom&&m(h)},createCSS:function(h,j){q.w3cdom&&F(h,j)},addDomLoadEvent:c,addLoadEvent:d,getQueryParamValue:function(h){var j=r.location.search||r.location.hash;if(h==null)return J(j);if(j){j=
j.substring(1).split("&");for(var n=0;n<j.length;n++)if(j[n].substring(0,j[n].indexOf("="))==h)return J(j[n].substring(j[n].indexOf("=")+1))}return""},expressInstallCallback:function(){if(N&&O){var h=l(y);if(h){h.parentNode.replaceChild(O,h);if(W){A(W,true);if(q.ie&&q.win)O.style.display="block"}W=O=null;N=false}}}}}();var DEBUG=false,userLoggedIn=false,loggedInUserId,loggedInUserName,userAccessToken,friends={},likes={},albumInfo={},photosInfo={},locationInfo={},geocodeInfo={},birthdayInfo={},pictureInfo={},genderInfo={},mutualFriends={},totalFriends={},totalLikes={},mutualLikes={},educationInfo={},activityData={},MONTHS=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],map,infowindow,geocoder=new google.maps.Geocoder,lat_min=90,lat_max=-90,lng_min=180,lng_max=-180,FeedLoadComplete=true,
OFFSETCOUNT=50,AlbumsLoaded=false,activityloadcount=0,albumsLoading=false,progressbarobj=new UProgressBar({elid:"waiting",min:0,max:0,value:0});function captureAlbumInfo(){log("Start of captureAlbumInfo");for(var a=countItems(friends),b=0;b<a;){var c=function(d){return function(){revealAlbumInfo(d)}}(constructPartialCsv(friends,b,b+100));window.setTimeout(c,b*100);b+=100}AlbumsLoaded=true}
var revealAlbumInfo=function(a){log("Started loading album information");url="/albums?fields=id,name,count,link";FB.api(url,{limit:100,ids:a},function(b){if(b.error)AlbumsLoaded=true;else{constructCsv(friends);for(var c in b)if(b.hasOwnProperty(c)){var d=b[c].data,f=0,e=0;if(d&&d.length){f=d.length;for(var g in d)if(d.hasOwnProperty(g)){var k=d[g].count?parseInt(d[g].count):0;e+=k}}albumInfo[c]=(albumInfo[c]?parseInt(albumInfo[c]):0)+f;photosInfo[c]=(photosInfo[c]?parseInt(photosInfo[c]):0)+e}AlbumsLoaded=
true;log("Completed loading album information")}})};function getAlbumsForDropdown(){var a=document.getElementById("friendsalbumselect").value;if(!a||a==""||a=="-1")a="me";getAlbumsForUser(a)}
var getAlbumsForUser=function(a,b){if(!albumsLoading){albumsLoading=true;var c="<br><br>Loading "+friends[a]+"&apos;s Albums<br><br>";document.getElementById("album_detail").innerHTML=c;b||(b="/"+a+"/albums?fields=id,name,count,link,from,description,created_time,location,comments");FB.api(b,{limit:100},function(d){var f=[""];if(d.error)albumsLoading=false;else{if((d=d.data)&&d.length)for(var e in d)if(d.hasOwnProperty(e)){var g=d[e].id,k=d[e].name,i=d[e].link,m=d[e].created_time;m=m?m.getDateFromfacebookFormat().getFormattedDate():
"";var o=d[e].count,l=d[e].location,s=d[e].description,v=0;if(d[e].comments)v=d[e].comments.data.length;f.push('<div class="albumbox"><a href="',i,'" target="new">');f.push('<div class="bold">',k,"</div>");f.push('<div class="albumimage" style="background-image:url(https://graph.facebook.com/',g,"/picture?access_token=",userAccessToken,');"></div>');f.push('</a><div class="albumtext"><span>',m,"<br>Photos:",o);l&&f.push("<br>Location: ",l);f.push("<br>Comments: ",v);s&&f.push("<br><br>",s);f.push("</span></div>");
f.push("</div>")}c="<br>";if(albumsLoading){document.getElementById("album_detail").innerHTML=c+f.join("");albumsLoading=false}}})}},getPhotosForUser=function(a,b){if(!albumsLoading){albumsLoading=true;var c="<br><br>Loading "+friends[a]+"&apos;s Photos<br><br>";document.getElementById("album_detail").innerHTML=c;b||(b="/"+a+"/albums?fields=id");FB.api(b,{limit:50},function(d){var f=[""];if(d.error)albumsLoading=false;else{if((d=d.data)&&d.length)for(var e in d)d.hasOwnProperty(e)&&f.push(d[e].id,
",");f=f.join("");window.setTimeout('getPhotosForAlbums("'+f.substring(0,f.length-1)+'")',200)}})}},getPhotosForAlbums=function(a){url="/photos?ids="+a+"&fields=id,link,picture,icon,from";FB.api(url,{limit:100},function(b){document.getElementById("album_detail");var c=[""];if(!b.error){var d=b.data,f=0,e;for(e in b)if(b.hasOwnProperty(e)){if((d=b[e].data)&&d.length)for(var g in d)if(d.hasOwnProperty(g)){c.push('<a href="',d[g].link,'" target="new"><div class="picturebox" style="background-image:url(',
d[g].picture,');"></div></a>');f++;if(f>500){c.push('<br><div style="clear:both;color:#999999">(Only 500 photos displayed)</div>');break}}if(f>500)break}htmlText="<br>";document.getElementById("album_detail").innerHTML=htmlText+c.join("")}albumsLoading=false})},displayAlbumInfo=function(){$("#friendsalbumselect").change(getAlbumsForDropdown);var a="Album and Photo information of all your "+countItems(friends)+" friends on Facebook<br>";a+='<table class="orange"><thead><tr><th>ID</th><th>Name</th><th>Albums</th><th>Photos</th></tr></thead>';
var b="odd",c;for(c in albumInfo)if(albumInfo.hasOwnProperty(c)){b=b=="odd"?"":"odd";a+='<tr class="'+b+'"><td><img src="'+pictureInfo[c]+'"></td><td>'+friends[c]+"</td><td>"+albumInfo[c]+"</td><td>"+photosInfo[c]+"</td></tr>"}drawAlbumChart();drawPhotoChart()},displayLocationInfo=function(){drawLocationTable();var a=countItems(locationInfo),b=countItems(geocodeInfo);if(b+1!=a){progressbarobj.setMaxValue(a);progressbarobj.setValue(b);log("Still waiting for the address geocoding.. Waiting..");setTimeout("displayLocationInfo()",
1E3)}else{dropMarkers();log("Drawing map complete")}},displayBirthdayInfo=function(){displayCurrentYear();displayUpcomingBirthdays();drawBirthdayTable()};
function drawAlbumChart(){var a=[],b;for(b in albumInfo)albumInfo.hasOwnProperty(b)&&a.push([b,albumInfo[b]]);a.sort(function(f,e){return e[1]-f[1]});b=[];for(var c=0;c<a.length;c++){if(c==10)break;log("Adding "+friends[a[c][0]]+" and "+a[c][1]+" to the album list");var d=[];d.push(a[c][0]);d.push(a[c][1]);b.push(d)}highalbumoptions.series[0].data=b;new Highcharts.Chart(highalbumoptions)}
function drawPhotoChart(){var a=[],b;for(b in photosInfo)photosInfo.hasOwnProperty(b)&&a.push([b,photosInfo[b]]);a.sort(function(f,e){return e[1]-f[1]});b=[];for(var c=0;c<a.length;c++){if(c==10)break;log("Adding "+friends[a[c][0]]+" and "+a[c][1]+" to the photo list");var d=[];d.push(a[c][0]);d.push(a[c][1]);b.push(d)}highphotooptions.series[0].data=b;new Highcharts.Chart(highphotooptions)}
function drawGenderChart(){var a=[],b;for(b in genderInfo)if(genderInfo.hasOwnProperty(b)){var c=[];c.push(b);c.push(genderInfo[b].length);a.push(c)}highgenderoptions.series[0].data=a;new Highcharts.Chart(highgenderoptions)}function drawEducationChart(){var a=[],b;for(b in educationInfo)if(educationInfo.hasOwnProperty(b)){var c=[];c.push(b);c.push(educationInfo[b].length);a.push(c)}higheducationoptions.series[0].data=a;new Highcharts.Chart(higheducationoptions)}
function initialize(){var a={zoom:8,center:new google.maps.LatLng(17.4,78.6),mapTypeId:google.maps.MapTypeId.ROADMAP};map=new google.maps.Map(document.getElementById("map_canvas"),a);infowindow=new google.maps.InfoWindow;google.maps.event.addListener(map,"click",function(){hideInfoWindow()})}function dropMarkers(){initialize();var a=0,b;for(b in locationInfo)!locationInfo.hasOwnProperty(b)||b=="Unknown"||function(c,d){setTimeout(function(){displayOnMap(c,d)},a++*0)}(b,locationInfo[b])}
var localSearch,localSearchCounter=0,locationArray=[];function localSearchComplete(){if(localSearch.results&&localSearch.results.length>0){var a=new google.maps.LatLng(localSearch.results[0].lat,localSearch.results[0].lng);geocodeInfo[locationArray[localSearchCounter]]=a}else geocodeInfo[locationArray[localSearchCounter]]=null;localSearchCounter++;localSearchNextAddress()}
function convertLocationToArray(){for(var a in locationInfo)!locationInfo.hasOwnProperty(a)||a=="Unknown"||(locationArray[locationArray.length]=a)}function localSearchNextAddress(){if(!(localSearchCounter>=locationArray.length)){var a=locationArray[localSearchCounter];localSearch=new google.search.LocalSearch;localSearch.setSearchCompleteCallback(this,localSearchComplete,null);localSearch.execute(a)}}
function geocodeAllAddresses(){var a=0,b;for(b in locationInfo)if(!(!locationInfo.hasOwnProperty(b)||b=="Unknown")){log("Geocode "+b+" request created");(function(c){setTimeout(function(){geocodeAddress(c)},a++*800)})(b)}}function geocodeAddress(a){geocoder.geocode({address:a},function(b,c){if(c==google.maps.GeocoderStatus.OK){geocodeInfo[a]=b[0].geometry.location;log("Geocoded "+a+" to "+b[0].geometry.location.toString())}else{geocodeInfo[a]=null;log("Could not geocode "+a+" - Reason: "+c)}})}
function displayOnMap(a,b){var c=geocodeInfo[a];if(c){map.setCenter(c);var d=c.lat(),f=c.lng();if(d<lat_min)lat_min=d;if(d>lat_max)lat_max=d;if(f<lng_min)lng_min=f;if(f>lng_max)lng_max=f;for(d=0;d<b.length;d++){f=new google.maps.Marker({map:map,icon:"yellow-markers/marker"+b.length+".png",position:c,animation:google.maps.Animation.DROP,draggable:false,clickable:true});google.maps.event.addListener(f,"click",function(){moreDetail(c,b,a)})}map.fitBounds(new google.maps.LatLngBounds(new google.maps.LatLng(lat_min,
lng_min),new google.maps.LatLng(lat_max,lng_max)))}}function hideInfoWindow(){infowindow.close()}function moreDetail(a,b,c){infowindow.setPosition(a);a="";a+="<b>"+b.length+" friend"+(b.length==1?"":"s")+" in "+c+"</b><br>";for(c=0;c<b.length;c++){a+='<img src="'+pictureInfo[b[c]]+'" title="'+friends[b[c]]+'">&nbsp;';if(c%5==4)a+="<br>"}infowindow.setContent(a);infowindow.open(map)}function countItems(a){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b}
function constructCsv(a){var b="",c;for(c in a)if(a.hasOwnProperty(c))b+=c+",";return b.substring(0,b.length-1)}
function displayBirthdays(a,b,c){a=['<div style="width:100%">'];var d=0,f;for(f in birthdayInfo)if(!(f=="Unknown"||!birthdayInfo.hasOwnProperty(f)))if(f==b){var e=birthdayInfo[f];total=0;for(var g in e)if(e.hasOwnProperty(g))if(!(g=="Unknown"||c&&c!=g))for(var k=0;k<e[g].length;k++){d++;a.push('<div class="userbox"><img src="',pictureInfo[e[g][k]],'" align="left">&nbsp;',MONTHS[b-1],"&nbsp;",g,"<br>&nbsp;<b>",friends[e[g][k]],"</b></div>")}}a.push('<div style="clear:both"></div>');a.push("</div>");
b="<br><b>"+(d==0?"No":d)+" friends with birthdays "+(c?"on ":"in ")+MONTH_NAMES[b-1]+" "+(c?c:"")+"</b><br><br>";document.getElementById("calendar_div_detail").innerHTML=b+a.join("")}
function displayUpcomingBirthdays(){var a=0,b=0,c=new Date,d=c.getMonth();c=c.getDate();var f=['<div style="width:350px">'];f.push('<span class="bold"><u>Upcoming birthdays</u>:</span>');if(countItems(birthdayInfo)!=0){var e=d+1;do{var g=birthdayInfo[e],k;for(k in g)if(g.hasOwnProperty(k))if(!(k=="Unknown"||parseInt(k,10)<parseInt(c,10)&&e==d+1)){for(var i=0;i<g[k].length;i++){a++;i==0?f.push("<br><b>",MONTHS[e-1],"&nbsp;",k,"</b>&nbsp;-&nbsp;",friends[g[k][i]]):f.push(",&nbsp;",friends[g[k][i]]);
if(a>5)break}if(a>5)break}if(a>5)break;e++;b++;if(e>12)e=1}while(a<5||b>1)}else f.push("None in the next 2 months");f.push("</div><br>");document.getElementById("upcoming_div_detail").innerHTML=f.join("")}
function displayAllFriends(){var a=[""],b;for(b in pictureInfo)friends[b]?a.push('<div class="userbox"><img src="',pictureInfo[b],'" align="left">&nbsp;<b>',friends[b],"</b></div>"):a.push('<div class="userbox"><img src="',pictureInfo[b],'" align="left">&nbsp;<b>',"You","</b></div>");document.getElementById("friendsBlock").innerHTML+=a.join("")}function initCaps(a){if(a&&a.length>0)a=a.substr(0,1).toUpperCase()+a.substring(1,a.length);return a}
function log(a){if(DEBUG){document.getElementById("debugLog").innerHTML=new Date+" => "+a+"<br>"+document.getElementById("debugLog").innerHTML;window.console&&console.log(new Date+" => "+a)}}function formatData(a){return a}function reloadTimeline(){var a=document.getElementById("friendselect").value;if(!a||a==""||a=="-1")a="me";displayTimeline(a)}function displayTimeline(a){$("#friendselect").change(reloadTimeline);if(FeedLoadComplete){FeedLoadComplete=false;clearTimeline();retrieveFeedInfo(a)}}
var retrieveFeedInfo=function(a,b){log("<br>retrieveFeedInfo with offset : "+b);a||(a="me");var c={};c.limit=OFFSETCOUNT;if(b)c.until=b;url="/"+a+"/feed?fields=id,type,message,likes,comments,from";FB.api(url,c,function(d){if(d.error)FeedLoadComplete=true;else{var f="",e=[];if(d.paging&&d.paging.next){f=d.paging.next;f=f.substring(f.indexOf("until=")+6);if(f.indexOf("&")!=-1)f=f.substring(0,f.indexOf("&"))}if(d.data)if((d=d.data)&&d.length){log(d.length+" posts retrieved");for(var g in d)if(d.hasOwnProperty(g)){var k=
d[g].id,i=k.substring(k.indexOf("_")+1),m=k.substring(0,k.indexOf("_")),o=formatData(d[g].message),l=d[g].created_time,s="Status Update";k=m;if(d[g].from&&d[g].from.id!=m){k=m;m=d[g].from.id;s="Posted by "+d[g].from.name}if(d[g].type!="link"){if(d[g].type=="video")o="(video)";var v=[];if(d[g].comments&&d[g].comments.data){o&&o!=""&&v.push({postid:i,user:k,friendid:m,title:s,message:o,createdtime:l});for(var F=d[g].comments.data,A=0;A<F.length;A++){o=F[A];m=o.from.id;(o=o.message)&&o!=""&&v.push({postid:i,
user:k,friendid:m,title:s,message:o,createdtime:l})}v.reverse()}else o&&o!=""&&v.push({postid:i,user:k,friendid:m,title:s,message:o,createdtime:l});e=e.concat(v)}}}e.length>0&&updateTimeline(e);if(f&&f!=""){f=parseInt(f,10)-1;FeedLoadComplete=false;retrieveFeedInfo(k,f)}else FeedLoadComplete=true}})};
function createFriendsDropdown(){var a=[],b;for(b in friends)friends.hasOwnProperty(b)&&a.push([b,friends[b]]);a.sort(function(f,e){var g=f[1],k=e[1];if(g==k)return 0;if(g>k)return 1;if(g<k)return-1});b=document.createElement("select");b.setAttribute("id","friendselect");b.options[b.options.length]=new Option("You","me",true,true);var c=document.createElement("select");c.setAttribute("id","friendsalbumselect");c.options[c.options.length]=new Option("You","me",true,true);for(var d=0;d<a.length;d++){b.options[b.length]=
new Option(a[d][1],a[d][0],false,false);c.options[c.length]=new Option(a[d][1],a[d][0],false,false)}document.getElementById("friendsList").appendChild(b);document.getElementById("friendsAlbumList").appendChild(c)}
function displayFriendSphere(){var a=new google.visualization.DataTable;a.addColumn("string","Name");a.addColumn("string","ID");a.addRows(countItems(friends));var b=0,c;for(c in friends)if(friends.hasOwnProperty(c)){var d=c;a.setCell(b,0,friends[c]);a.setCell(b,1,d);b++}(new gviz_word_cumulus.WordCumulus(document.getElementById("friendsSphere"))).draw(a,{text_color:"#663300",hover_text_color:"#000066",speed:1,width:900,height:600})}
function displayMutualFriendInfo(){countItems(mutualFriends)==0&&FB.api({method:"fql.multiquery",queries:{query1:"SELECT uid2 FROM friend WHERE uid1 = me()",query2:"SELECT uid1, uid2 FROM friend WHERE uid1 IN (SELECT uid2 FROM #query1) AND uid2 IN (SELECT uid2 FROM #query1)"}},function(a){mutualFriends={};var b=a[1].fql_result_set;for(a=0;a<b.length;a++){var c=b[a],d=c.uid1;mutualFriends[d]||(mutualFriends[d]=[]);mutualFriends[d][mutualFriends[d].length]=c.uid2}b=[];for(a in mutualFriends)b.push([a,
mutualFriends[a].length]);b.sort(function(f,e){return e[1]-f[1]});a=[];c=[];for(d=0;d<b.length;d++){a.push(friends[b[d][0]]);c.push(b[d][1])}highfriendoptions.xAxis.categories=a;highfriendoptions.series[0].data=c;new Highcharts.Chart(highfriendoptions)})}function loadLikesInfo(){FB.api("/me/likes",function(a){for(var b=0;b<a.data.length;b++)likes[a.data[b].id]=a.data[b].name})}
function displayTotals(){countItems(totalFriends)!=0||countItems(totalLikes)!=0||FB.api({method:"fql.multiquery",queries:{query1:"SELECT uid2 FROM friend WHERE uid1 = me()",query2:"SELECT uid, name, friend_count, likes_count FROM user WHERE uid IN (SELECT uid2 FROM #query1)"}},function(a){var b=a[1].fql_result_set;for(a=0;a<b.length;a++){var c=b[a],d=c.uid;totalFriends[d]=c.friend_count;totalLikes[d]=c.likes_count}c=[];for(a in totalFriends)totalFriends[a]!=null&&c.push([a,parseInt(totalFriends[a])]);
c.sort(function(e,g){return g[1]-e[1]});d=[];var f=[];for(b=0;b<c.length;b++){d.push(friends[c[b][0]]);f.push(c[b][1])}hightotalfriendoptions.xAxis.categories=d;hightotalfriendoptions.series[0].data=f;new Highcharts.Chart(hightotalfriendoptions);c=[];for(a in totalLikes)totalLikes[a]!=null&&c.push([a,parseInt(totalLikes[a])]);c.sort(function(e,g){return g[1]-e[1]});a=[];d=[];for(b=0;b<c.length;b++){a.push(friends[c[b][0]]);d.push(c[b][1])}hightotallikeoptions.xAxis.categories=a;hightotallikeoptions.series[0].data=
d;new Highcharts.Chart(hightotallikeoptions)})}
function displayMutualLikesInfo(){countItems(mutualLikes)==0&&FB.api({method:"fql.query",query:"select uid, page_id, type  from page_fan where page_id in (select page_id from page_fan where uid = me()) and uid  in (select uid2 from friend where uid1=me())"},function(a){mutualLikes={};for(var b=0;b<a.length;b++){var c=a[b],d=c.page_id;mutualLikes[d]||(mutualLikes[d]=[]);mutualLikes[d][mutualLikes[d].length]=c.uid}a=[];for(b in mutualLikes)a.push([b,mutualLikes[b].length]);a.sort(function(f,e){return e[1]-
f[1]});b=[];c=[];for(d=0;d<a.length;d++){b.push(likes[a[d][0]]);c.push(a[d][1])}highlikeoptions.xAxis.categories=b;highlikeoptions.series[0].data=c;new Highcharts.Chart(highlikeoptions)})}String.prototype.getDateFromfacebookFormat=function(){var a=this.split(/[-:T+]/);a[1]-=1;a.pop();return new Date(Date.UTC.apply(Date,a))};Date.prototype.getFormattedDate=function(){return this.getDate()+" "+MONTHS[this.getMonth()]+" "+this.getFullYear()};
Date.prototype.getFormattedDateTime=function(){var a="PM",b=this.getHours();if(b<12)a="AM";if(b==0)b=12;else if(b>12)b-=12;var c=""+this.getMinutes();if(c.length==1)c="0"+c;var d=""+this.getSeconds();if(d.length==1)d="0"+d;return this.getDate()+" "+MONTHS[this.getMonth()]+" "+this.getFullYear()+" "+b+":"+c+":"+d+" "+a};if(!Array.indexOf)Array.prototype.indexOf=function(a){for(var b=0;b<this.length;b++)if(this[b]==a)return b;return-1};var polltime=30,lastpolltime=0,searchtimer,searchStr,individualtimers=[];$(function(){$("#searchStr").keyup(function(a){var b=document.getElementById("searchStr").value;a.keyCode==13&&b!=""&&searchFacebook()})});
function searchFacebook(){searchStr=document.getElementById("searchStr").value;if(searchStr!=""){searchtimer&&window.clearTimeout(searchtimer);for(var a=0;a<individualtimers.length;a++)individualtimers[a]&&window.clearTimeout(individualtimers[a]);lastpolltime=0;$("#searchResults .item").removeClass("border").html("");continueSearching()}}
function continueSearching(){var a={};a.limit=10;FB.api("/search?q="+searchStr+"&type=post",a,function(b){b.error||displaySearchResults(b.data)});searchtimer=window.setTimeout("continueSearching();",35E3)}function displaySearchResults(a){for(var b=a.length,c=polltime/b,d=0;d<b;d++)individualtimers[d]=window.setTimeout(function(f){return function(){addNewElement(a[b-f-1])}}(d),c*1E3*d)}
function addNewElement(a){var b=a.created_time;b=b.getDateFromfacebookFormat().getTime();if(!(lastpolltime>=b)){if(lastpolltime<b)lastpolltime=b;b=new Date(b);$("#searchResults .item:last").remove();var c='<img src="http://graph.facebook.com/'+a.from.id+'/picture">',d="";if(a.message)d+=a.message;if(a.name)d+="&nbsp;&nbsp;"+a.name;if(a.description)d+="&nbsp;&nbsp;"+a.description;d=d.replace(RegExp(searchStr,"gi"),'<span style="background-color:#FFFBF0;font-weight:bold">'+searchStr+"</span>");c='<table border="0" cellpadding="5" cellspacing="2"><tr><td width="60" align="center">'+
c+'</td><td><a target="_blank" href="http://www.facebook.com/'+a.from.id+"/posts/"+a.id.substring(a.id.indexOf("_")+1)+'"><b>'+a.from.name+"</b></a> &nbsp;:&nbsp;"+d+(a.type=="video"?' <span style="color:#4D2600">[Video]</span>':"")+"<br><br>";if(a.icon)c+='<img src="'+a.icon+'">&nbsp;';c+='<span style="color:#999999">'+b+"</span></td></tr></table>";$("<div>").addClass("item").addClass("border").css("opacity","1").html(c).insertBefore("#searchResults .item:first").hide().fadeIn(1E3)}};var activitychart=null;function constructPartialCsv(a,b,c){var d="",f=0,e;for(e in a)if(f<b)f++;else if(f>=c)break;else if(a.hasOwnProperty(e)){d+=e+",";f++}return d.substring(0,d.length-1)}
function captureActivityMetrics(){if(!(activityoptions.xAxis.categories.length>0)){activitychart=new Highcharts.Chart(activityoptions);log("Start of captureActivityMetrics");var a=new Date;a=a.setDate(a.getDate()-7);for(var b=countItems(friends),c=0;c<b;){var d=function(f,e){return function(){retrieveActivityInfo(f,parseInt(e/1E3,10))}}(constructPartialCsv(friends,c,c+10),a);activityloadcount++;window.setTimeout(d,c*100);c+=10}refreshActivityChart()}}
function refreshActivityChart(){if(activityloadcount==0){displayActivityChart();document.getElementById("activityincompletemsg").innerHTML=""}else window.setTimeout("refreshActivityChart()",1E3)}
function displayActivityChart(){var a=activityoptions.xAxis.categories||[],b=activityoptions.series[0].data||[],c=activityoptions.series[1].data||[],d=activityoptions.series[2].data||[],f=activityoptions.series[3].data||[],e=activityoptions.series[4].data||[],g;for(g in activityData)if(activityData.hasOwnProperty(g)){a.push(friends[g]);b.push(activityData[g].V);c.push(activityData[g].S);d.push(activityData[g].L);f.push(activityData[g].P);e.push(activityData[g].O)}activitychart.xAxis[0].setCategories(a,
false);activitychart.series[0].setData(b,false);activitychart.series[1].setData(c,false);activitychart.series[2].setData(d,false);activitychart.series[3].setData(f,false);activitychart.series[4].setData(e,false);activitychart.redraw()}
var retrieveActivityInfo=function(a,b){log("<br>retrieveActivityInfo with offset : "+b);var c={};c.limit=100;if(b)c.since=b;url="/feed?ids="+a+"&fields=id,type,message,likes,comments,from";FB.api(url,c,function(d){activityloadcount--;if(!d.error){for(var f in d)if(d.hasOwnProperty(f)){var e=d[f].data,g=0,k=0,i=0,m=0,o=0,l;for(l in e)if(e[l].type=="status")g++;else if(e[l].type=="video")k++;else if(e[l].type=="link")i++;else if(e[l].type=="photo")o++;else e[l].type&&m++;if(k!=0||g!=0||i!=0||o!=0||
m!=0){e={};e.V=k;e.S=g;e.L=i;e.P=o;e.O=m;activityData[f]=e}}displayActivityChart()}})},activityoptions={chart:{renderTo:"highactivity",defaultSeriesType:"column"},title:{text:"Profile Activity Chart"},subtitle:{text:"(Whose profile is the most active in the last 7 days?)"},credits:{enabled:false},xAxis:{labels:{enabled:false},categories:[]},yAxis:{min:0,title:{text:"Number of posts"}},tooltip:{formatter:function(){total=this.point.stackTotal==100?"100+":this.point.stackTotal;return"<b>"+this.x+"</b><br/>"+
this.series.name+": "+this.y+"<br/>Total: "+total}},plotOptions:{column:{stacking:"normal"}},series:[{name:"Videos",data:[]},{name:"Status",data:[]},{name:"Links",data:[]},{name:"Photos",data:[]},{name:"Others",data:[]}]};Highcharts.setOptions({colors:["#4572A7","#AA4643","#89A54E","#80699B","#3D96AE","#DB843D","#919400","#92A8CD","#A47D7C","#B5CA92"],credits:{text:"Spectrum on Facebook",href:"http://www.facebook.com/apps/application.php?id=132839880113484&sk=wall"}});
var highlikeoptions={chart:{renderTo:"highlikes"},title:{text:"Mutual Likes"},subtitle:{text:"(How many of your friends like what you like)"},xAxis:{labels:{enabled:false},categories:[]},yAxis:{title:{text:null}},tooltip:{formatter:function(){return"<b>"+this.x+"</b><br>"+this.y+" friends like it too"}},series:[{type:"column",name:"Number of friends"}]},highfriendoptions={chart:{renderTo:"highfriends"},title:{text:"Mutual Friends"},subtitle:{text:"(How many friends do you have in common)"},xAxis:{labels:{enabled:false},
categories:[]},yAxis:{title:{text:null}},tooltip:{formatter:function(){return"<b>"+this.x+"</b><br>"+this.y+" mutual friends"}},series:[{type:"column",name:"Number of friends"}]},hightotalfriendoptions={chart:{renderTo:"hightotalfriends"},title:{text:"Friends of Friends"},subtitle:{text:"(How many friends do your friends have)"},xAxis:{labels:{enabled:false},categories:[]},yAxis:{title:{text:null}},tooltip:{formatter:function(){return"<b>"+this.x+"</b><br>"+this.y+" friends"}},series:[{type:"column",
name:"Number of friends"}]},hightotallikeoptions={chart:{renderTo:"hightotallikes"},title:{text:"Friends Likes"},subtitle:{text:"(How many likes do your friends have)"},xAxis:{labels:{enabled:false},categories:[]},yAxis:{title:{text:null}},tooltip:{formatter:function(){return"<b>"+this.x+"</b><br>"+this.y+" likes"}},series:[{type:"column",name:"Number of Likes"}]},highalbumoptions={chart:{renderTo:"highalbums",plotShadow:true},title:{text:"Top 10 friends with most number of albums"},legend:{labelFormatter:function(){return friends[this.name]},
layout:"vertical",align:"right",verticalAlign:"top",x:0,y:50,borderWidth:0},tooltip:{formatter:function(){return"<b>"+friends[this.point.name]+"</b><br>"+this.y+" albums"}},plotOptions:{pie:{allowPointSelect:true,cursor:"pointer",dataLabels:{enabled:false},showInLegend:true,point:{events:{click:function(){getAlbumsForUser(this.name)}}}}},series:[{type:"pie",name:"Number of Albums"}]},highphotooptions={chart:{renderTo:"highphotos",plotShadow:true},title:{text:"Top 10 friends with most number of photos"},
legend:{labelFormatter:function(){return friends[this.name]},layout:"vertical",align:"right",verticalAlign:"top",x:0,y:50,borderWidth:0},tooltip:{formatter:function(){return"<b>"+friends[this.point.name]+"</b><br>"+this.y+" photos"}},plotOptions:{pie:{allowPointSelect:true,cursor:"pointer",dataLabels:{enabled:false},showInLegend:true,point:{events:{click:function(){getPhotosForUser(this.name)}}}}},series:[{type:"pie",name:"Number of Photos"}]},highgenderoptions={chart:{renderTo:"highgender",plotShadow:true},
title:{text:"Gender distribution of your friends"},legend:{layout:"vertical",align:"right",verticalAlign:"top",x:0,y:50,borderWidth:0},tooltip:{formatter:function(){return"<b>"+this.point.name+"</b> : "+this.y}},plotOptions:{pie:{allowPointSelect:true,cursor:"pointer",dataLabels:{enabled:false},showInLegend:true}},series:[{type:"pie",name:"Gender"}]},higheducationoptions={chart:{renderTo:"higheducation",plotShadow:true},title:{text:"Education distribution of your friends"},legend:{layout:"vertical",
align:"right",verticalAlign:"top",x:0,y:50,borderWidth:0},tooltip:{formatter:function(){return"<b>"+this.point.name+"</b> : "+this.y}},plotOptions:{pie:{allowPointSelect:true,cursor:"pointer",dataLabels:{enabled:false},showInLegend:true}},series:[{type:"pie",name:"Education"}]};function exportContentsToPdf(){if($("input[name='exportitems']:checked").length!=0){var a={},b=[],c;for(c in pictureInfo){var d={};d.id=c;d.name=friends[c];d.imageUrl=pictureInfo[c];b.push(d)}var f=[],e;for(e in educationInfo)if(educationInfo.hasOwnProperty(e)){d={};d.education=e;d.count=educationInfo[e].length;f.push(d)}var g=[];for(e in genderInfo)if(genderInfo.hasOwnProperty(e)){d={};d.gender=e;d.count=genderInfo[e].length;g.push(d)}var k=[];c=[];for(e in albumInfo)albumInfo.hasOwnProperty(e)&&
c.push([e,albumInfo[e]]);c.sort(function(l,s){return s[1]-l[1]});for(var i=0;i<c.length;i++){if(i==10)break;d={};d.album=friends[c[i][0]];d.count=c[i][1];k.push(d)}var m=[];c=[];for(e in photosInfo)photosInfo.hasOwnProperty(e)&&c.push([e,photosInfo[e]]);c.sort(function(l,s){return s[1]-l[1]});for(i=0;i<c.length;i++){if(i==10)break;d={};d.photo=friends[c[i][0]];d.count=c[i][1];m.push(d)}var o=document.createElement("form");o.setAttribute("method","post");o.setAttribute("id","exportform");o.setAttribute("action",
"http://facebookspectrum.appspot.com/export.pdf");$.each($("input[name='exportitems']:checked"),function(){log("Checked "+$(this).val());var l=$(this).val(),s=document.createElement("input");s.setAttribute("type","hidden");s.setAttribute("name",l);s.setAttribute("value","1");o.appendChild(s);switch(l){case "user":a.user=b;break;case "education":a.education=f;break;case "gender":a.gender=g;break;case "album":a.album=k;break;case "photo":a.photo=m;break;default:log("Invalid selection")}});d=JSON.stringify(a);
hiddenField=document.createElement("input");hiddenField.setAttribute("type","hidden");hiddenField.setAttribute("name","data");hiddenField.setAttribute("value",d);o.appendChild(hiddenField);hiddenField=document.createElement("input");hiddenField.setAttribute("type","hidden");hiddenField.setAttribute("name","name");hiddenField.setAttribute("value",loggedInUserName);o.appendChild(hiddenField);document.body.appendChild(o);$("#exportmsg").show();window.setTimeout('$("#exportmsg").hide()',2E4);o.submit()}}
;
