var MONTH_NAMES=["January","February","March","April","May","June","July","August","September","October","November","December"],DOW=["S","M","T","W","T","F","S"],DAYS_IN_MONTH=[31,28,31,30,31,30,31,31,30,31,30,31],SHOW_MONTH="Click to display this month";function isLeapYear(a){a=a.getFullYear();if(a%4==0&&a%100!=0)return true;return a%400==0}function displayCurrentYear(a){a=a||(new Date).getFullYear();showYear(a)}
function getDaysInMonth(a){var b=DAYS_IN_MONTH[a.getMonth()];return b==28&&isLeapYear(a)?29:b}function getWeeksInMonth(a,b){var c=new Date(a,b,1),d=c.getDay();c=getDaysInMonth(c);return Math.ceil((d+c)/7)}
function getMonthHtml(a,b,c,d){var e=new Date,f=e.getFullYear(),g=e.getMonth();e=e.getDate();a.push('<table class="month" border=0 cellspacing=0>','<tr><td colspan=7 title="',SHOW_MONTH,'" class="monthHeader clickable" ','onclick="displayBirthdays(',b,",",c+1,')">',MONTH_NAMES[c],"<tr>");for(var k=0;k<DOW.length;++k)a.push('<td class="dow" style="color:black">',DOW[k]);k=new Date(b,c,1);var j=k.getDay(),n=getDaysInMonth(k),p=k=0;d=d||Math.ceil(n/7);for(j=1-j;;++j){var l=k++%7;if(d<=p&&l==0)break;
if(l==0){p>0&&a.push("</tr>");a.push("<tr>");++p}a.push('<td class="');var y="normal";if(b==f&&c==g&&j==e)y="today";if(j<=n&&(l==0||l==6))y="weekend ";a.push(y);if(j>=1&&j<=n)birthdayInfo[c+1]&&birthdayInfo[c+1][j]?a.push(' clickable" onclick="displayBirthdays(',b,",",c+1,",",j,')" title="',birthdayInfo[c+1][j].length,' friend(s)">',j):a.push('">',j);else a.push('">&nbsp;');a.push("</td>")}a.push("</tr></table>")}
function showYear(a){for(var b=["<table>"],c=0,d=0;d<12;++d){if(d%4==0){b.push("<tr>");c=Math.max(getWeeksInMonth(a,d),getWeeksInMonth(a,d+1),getWeeksInMonth(a,d+2),getWeeksInMonth(a,d+3))}b.push('<td class="outer">');getMonthHtml(b,a,d,c)}b.push("</table>");document.getElementById("calendar_div").innerHTML=b.join("")}var DARK_BLUE="#112aba",LIGHT_BLUE="#e8eef7",WEEKEND="#eee",WHITE="#fff",TODAY="#557799",TODAY_BORDER_DARK="#246",TODAY_BORDER_LIGHT="#9bd",BORDER_GREY="#a2bbd3",DIVIDER="#c3d9ff";
function getStyles(){var a=["<style>"];a.push(".month td {text-align: center; padding:2px 4px 1px}",".month,td.dow,td.monthHeader {background-color:",LIGHT_BLUE,"}","td.normal {background-color:",WHITE,"}","td.weekend {background-color:",WEEKEND,"}","td.outer {padding-right: 4px; padding-bottom: 4px; }","td.dow {border-width: 0 0 1px 0; border-style:solid;","border-color: ",DIVIDER,"}","td.today {padding: 1px 3px !important; background-color:",TODAY,";color:#fff !important; border-width: 1px; border-style:solid;",
"border-color: ",TODAY_BORDER_DARK," ",TODAY_BORDER_LIGHT," ",TODAY_BORDER_LIGHT," ",TODAY_BORDER_DARK,"}","td.monthHeader {font-weight:bold}",".month {background-color:",LIGHT_BLUE,";border: 1px solid ",BORDER_GREY,"}","body, td {font-family:Arial;font-size: 12.8px}","body {margin-left:10px; background-color:",WHITE,"}","td {vertical-align: top}",".clickable {font-weight:bold;cursor:pointer; color:",DARK_BLUE,"}",".clickable:hover {text-decoration: underline}");a.push("</style>");return a.join("")}
document.write(getStyles());function drawBirthdayTable(){var a=new google.visualization.DataTable;a.addColumn("number","Month");a.addColumn("number","Birthdays");a.addColumn("string","Friends");for(var b in birthdayInfo){var c=b;if(birthdayInfo.hasOwnProperty(b)){var d=birthdayInfo[b];if(b!="Unknown")b=MONTHS[b-1];var e="";total=0;for(var f in d)if(d.hasOwnProperty(f))for(var g=0;g<d[f].length;g++){e+=f=="Unknown"?friends[d[f][g]]+"<br>":"<b>"+f+"</b> - "+friends[d[f][g]]+"<br>";total++}b!="Unknown"&&a.addRow([{v:parseInt(c,
10),f:b},total,e])}}(new google.visualization.Table(document.getElementById("calendar_div_table"))).draw(a,{allowHtml:true})}
function drawLocationTable(){var a=new google.visualization.DataTable;a.addColumn("string","Location");a.addColumn("number","Count");a.addColumn("string","Friends");for(var b in locationInfo)if(locationInfo.hasOwnProperty(b)){for(var c=locationInfo[b],d=c.length,e="",f=0;f<c.length;f++)e+=f==0?friends[c[f]]:", "+friends[c[f]];b!="Unknown"&&a.addRow([b,d,e])}(new google.visualization.Table(document.getElementById("location_div_table"))).draw(a,{allowHtml:true})};var timeline,eventSource;
function createTimeline(){eventSource=new Timeline.DefaultEventSource;var a=document.getElementById("timeline_div"),b=Timeline.ClassicTheme.create();b.event.bubble.width=300;b.event.bubble.height=200;b.event.track.height=15;b.event.tape.height=8;b.timeline_start=new Date(Date.UTC(2005,10,1));b.timeline_stop=new Date(Date.UTC(2012,0,1));b=[Timeline.createBandInfo({width:"80%",intervalUnit:Timeline.DateTime.DAY,intervalPixels:500,eventSource:eventSource,theme:b,eventPainter:Timeline.CompactEventPainter,eventPainterParams:{iconWidth:25,
iconHeight:25,iconLabelGap:5,labelRightMargin:5,stackConcurrentPreciseInstantEvents:true},layout:"original"}),Timeline.createBandInfo({width:"10%",intervalUnit:Timeline.DateTime.MONTH,intervalPixels:200,eventSource:eventSource,theme:b,layout:"overview"}),Timeline.createBandInfo({width:"10%",intervalUnit:Timeline.DateTime.YEAR,intervalPixels:300,eventSource:eventSource,theme:b,layout:"overview"})];b[1].syncWith=0;b[1].highlight=true;b[2].syncWith=0;b[2].highlight=true;timeline=Timeline.create(a,b,
Timeline.HORIZONTAL);eventSource.loadJSON(timeline_data,".");timeline.layout()}var resizeTimerID=null;function onResize(){if(resizeTimerID==null)resizeTimerID=window.setTimeout(function(){resizeTimerID=null;timeline.layout()},500)}
function updateTimeline(a){timeline||createTimeline();var b=timeline_data;b.events=[];for(var c=0;c<a.length;c++){var d=a[c].postid,e=a[c].friendid,f=a[c].user,g=a[c].message,k=a[c].createdtime,j=k.getDateFromfacebookFormat().getTime(),n=timeline.timeline_start.getTime(),p=timeline.timeline_stop.getTime();if(j<n){n=new Date(j);n.setTime(n.getTime()+864E5);timeline.timeline_start=n}if(j>p){n=new Date(j);n.setTime(n.getTime()+864E5);timeline.timeline_stop=n}j=b.events.length;b.events[j]={};b.events[j].start=
k;b.events[j].description=g;b.events[j].textColor="#112aba";if(d!="")b.events[j].link="http://www.facebook.com/"+f+"/posts/"+d;b.events[j].image="http://graph.facebook.com/"+e+"/picture";b.events[j].icon="http://graph.facebook.com/"+e+"/picture"}eventSource.loadJSON(b,".")}function clearTimeline(){if(eventSource){eventSource.clear();timeline.layout()}}var timeline_data={dateTimeFormat:"iso8601",events:[]};
Timeline.DefaultEventSource.Event.prototype.fillInfoBubble=function(a,b,c){var d=a.ownerDocument,e=this.getLink(),f=this.getImage();if(f!=null){var g=d.createElement("img");g.src=f;b.event.bubble.imageStyler(g);a.appendChild(g)}f=d.createElement("div");g=d.createTextNode("View post on Facebook");if(e!=null){var k=d.createElement("a");k.href=e;k.setAttribute("target","new");k.appendChild(g);f.appendChild(k)}else f.appendChild(g);b.event.bubble.titleStyler(f);a.appendChild(f);e=d.createElement("div");
this.fillDescription(e);b.event.bubble.bodyStyler(e);a.appendChild(e);a.appendChild(d.createElement("br"));d=d.createElement("div");this.fillTime(d,c);b.event.bubble.timeStyler(d);a.appendChild(d)};Timeline.CompactEventPainter=function(a){this._params=a;this._onSelectListeners=[];this._frc=this._highlightMatcher=this._filterMatcher=null;this._eventIdToElmt={}};Timeline.CompactEventPainter.prototype.initialize=function(a,b){this._band=a;this._timeline=b;this._eventIdToElmt=this._highlightLayer=this._lineLayer=this._eventLayer=this._backLayer=null};Timeline.CompactEventPainter.prototype.addOnSelectListener=function(a){this._onSelectListeners.push(a)};
Timeline.CompactEventPainter.prototype.removeOnSelectListener=function(a){for(var b=0;b<this._onSelectListeners.length;b++)if(this._onSelectListeners[b]==a){this._onSelectListeners.splice(b,1);break}};Timeline.CompactEventPainter.prototype.getFilterMatcher=function(){return this._filterMatcher};Timeline.CompactEventPainter.prototype.setFilterMatcher=function(a){this._filterMatcher=a};Timeline.CompactEventPainter.prototype.getHighlightMatcher=function(){return this._highlightMatcher};
Timeline.CompactEventPainter.prototype.setHighlightMatcher=function(a){this._highlightMatcher=a};
Timeline.CompactEventPainter.prototype.paint=function(){var a=this._band.getEventSource();if(a!=null){this._eventIdToElmt={};this._prepareForPainting();var b=this._params.theme,c=b.event;b={trackOffset:"trackOffset"in this._params?this._params.trackOffset:10,trackHeight:"trackHeight"in this._params?this._params.trackHeight:10,tapeHeight:b.event.tape.height,tapeBottomMargin:"tapeBottomMargin"in this._params?this._params.tapeBottomMargin:2,labelBottomMargin:"labelBottomMargin"in this._params?this._params.labelBottomMargin:
5,labelRightMargin:"labelRightMargin"in this._params?this._params.labelRightMargin:5,defaultIcon:c.instant.icon,defaultIconWidth:c.instant.iconWidth,defaultIconHeight:c.instant.iconHeight,customIconWidth:"iconWidth"in this._params?this._params.iconWidth:c.instant.iconWidth,customIconHeight:"iconHeight"in this._params?this._params.iconHeight:c.instant.iconHeight,iconLabelGap:"iconLabelGap"in this._params?this._params.iconLabelGap:2,iconBottomMargin:"iconBottomMargin"in this._params?this._params.iconBottomMargin:
2};if("compositeIcon"in this._params){b.compositeIcon=this._params.compositeIcon;b.compositeIconWidth=this._params.compositeIconWidth||b.customIconWidth;b.compositeIconHeight=this._params.compositeIconHeight||b.customIconHeight}else{b.compositeIcon=b.defaultIcon;b.compositeIconWidth=b.defaultIconWidth;b.compositeIconHeight=b.defaultIconHeight}var d=this._band.getMinDate(),e=this._band.getMaxDate(),f=this._filterMatcher!=null?this._filterMatcher:function(){return true};c=this._highlightMatcher!=null?
this._highlightMatcher:function(){return-1};e=a.getEventIterator(d,e);a="stackConcurrentPreciseInstantEvents"in this._params&&this._params.stackConcurrentPreciseInstantEvents;if("collapseConcurrentPreciseInstantEvents"in this._params&&this._params.collapseConcurrentPreciseInstantEvents||a){d=[];for(var g=null;e.hasNext();){var k=e.next();if(f(k))if(!k.isInstant()||k.isImprecise())this.paintEvent(k,b,this._params.theme,c(k));else if(g!=null&&g.getStart().getTime()==k.getStart().getTime())d[d.length-
1].push(k);else{d.push([k]);g=k}}for(f=0;f<d.length;f++){e=d[f];if(e.length==1)this.paintEvent(e[0],b,this._params.theme,c(k));else{g=-1;for(var j=0;g<0&&j<e.length;j++)g=c(e[j]);a?this.paintStackedPreciseInstantEvents(e,b,this._params.theme,g):this.paintCompositePreciseInstantEvents(e,b,this._params.theme,g)}}}else for(;e.hasNext();){k=e.next();f(k)&&this.paintEvent(k,b,this._params.theme,c(k))}this._highlightLayer.style.display="block";this._lineLayer.style.display="block";this._eventLayer.style.display=
"block"}};Timeline.CompactEventPainter.prototype.softPaint=function(){};
Timeline.CompactEventPainter.prototype._prepareForPainting=function(){var a=this._band;if(this._backLayer==null){this._backLayer=this._band.createLayerDiv(0,"timeline-band-events");this._backLayer.style.visibility="hidden";var b=document.createElement("span");b.className="timeline-event-label";this._backLayer.appendChild(b);this._frc=SimileAjax.Graphics.getFontRenderingContext(b)}this._frc.update();this._tracks=[];this._highlightLayer!=null&&a.removeLayerDiv(this._highlightLayer);this._highlightLayer=
a.createLayerDiv(105,"timeline-band-highlights");this._highlightLayer.style.display="none";this._lineLayer!=null&&a.removeLayerDiv(this._lineLayer);this._lineLayer=a.createLayerDiv(110,"timeline-band-lines");this._lineLayer.style.display="none";this._eventLayer!=null&&a.removeLayerDiv(this._eventLayer);this._eventLayer=a.createLayerDiv(115,"timeline-band-events");this._eventLayer.style.display="none"};
Timeline.CompactEventPainter.prototype.paintEvent=function(a,b,c,d){a.isInstant()?this.paintInstantEvent(a,b,c,d):this.paintDurationEvent(a,b,c,d)};Timeline.CompactEventPainter.prototype.paintInstantEvent=function(a,b,c,d){a.isImprecise()?this.paintImpreciseInstantEvent(a,b,c,d):this.paintPreciseInstantEvent(a,b,c,d)};Timeline.CompactEventPainter.prototype.paintDurationEvent=function(a,b,c,d){a.isImprecise()?this.paintImpreciseDurationEvent(a,b,c,d):this.paintPreciseDurationEvent(a,b,c,d)};
Timeline.CompactEventPainter.prototype.paintPreciseInstantEvent=function(a,b,c,d){var e={tooltip:a.getProperty("tooltip")||a.getText()},f={url:a.getIcon()};if(f.url==null){f.url=b.defaultIcon;f.width=b.defaultIconWidth;f.height=b.defaultIconHeight}else{f.width=a.getProperty("iconWidth")||b.customIconWidth;f.height=a.getProperty("iconHeight")||b.customIconHeight}var g={text:a.getText(),color:a.getTextColor()||a.getColor(),className:a.getClassName()},k=this.paintTapeIconLabel(a.getStart(),e,null,f,
g,b,c,d),j=this;b=function(n,p){return j._onClickInstantEvent(k.iconElmtData.elmt,p,a)};SimileAjax.DOM.registerEvent(k.iconElmtData.elmt,"mousedown",b);SimileAjax.DOM.registerEvent(k.labelElmtData.elmt,"mousedown",b);this._eventIdToElmt[a.getID()]=k.iconElmtData.elmt};
Timeline.CompactEventPainter.prototype.paintCompositePreciseInstantEvents=function(a,b,c,d){for(var e=a[0],f=[],g=0;g<a.length;g++)f.push(a[g].getProperty("tooltip")||a[g].getText());f={tooltip:f.join("; ")};g={url:b.compositeIcon,width:b.compositeIconWidth,height:b.compositeIconHeight};var k={text:String.substitute(this._params.compositeEventLabelTemplate,[a.length])},j=this.paintTapeIconLabel(e.getStart(),f,null,g,k,b,c,d),n=this;b=function(p,l){return n._onClickCompositePreciseInstantEvent(j.iconElmtData.elmt,
l,a)};SimileAjax.DOM.registerEvent(j.iconElmtData.elmt,"mousedown",b);SimileAjax.DOM.registerEvent(j.labelElmtData.elmt,"mousedown",b);for(g=0;g<a.length;g++)this._eventIdToElmt[a[g].getID()]=j.iconElmtData.elmt};
Timeline.CompactEventPainter.prototype.paintStackedPreciseInstantEvents=function(a,b,c){for(var d=this._band,e=function(z){var s={url:z.getIcon()};if(s.url==null){s.url=b.defaultIcon;s.width=b.defaultIconWidth;s.height=b.defaultIconHeight}else{s.width=z.getProperty("iconWidth")||b.customIconWidth;s.height=z.getProperty("iconHeight")||b.customIconHeight}return s},f=e(a[0]),g=0,k=0,j=0,n=0,p=[],l=0;l<a.length;l++){var y=a[l],v=y.getText();y=e(y);var F=this._frc.computeSize(v);v={text:v,iconData:y,labelSize:F,
iconLeft:f.width+l*15-y.width};v.labelLeft=f.width+l*15+b.iconLabelGap;v.top=l*15;p.push(v);g=Math.min(g,v.iconLeft);j+=F.height;k=Math.max(k,v.labelLeft+F.width);n=Math.max(n,v.top+y.height)}k+=b.labelRightMargin;j+=b.labelBottomMargin;n+=b.iconBottomMargin;var t=function(z){return Math.round(d.dateToPixelOffset(z))}(a[0].getStart());e=[];v=Math.ceil(Math.max(n,j)/b.trackHeight);f=f.width+(a.length-1)*15;for(l=0;l<v;l++)e.push({start:g,end:f});g=Math.ceil(j/b.trackHeight);for(l=0;l<g;l++){j=e[l];
j.end=Math.max(j.end,k)}var J=this._fitTracks(t,e)*b.trackHeight+b.trackOffset,u=this._timeline.getDocument().createElement("div");u.className="timeline-event-icon-stack";u.style.position="absolute";u.style.overflow="visible";u.style.left=t+"px";u.style.top=J+"px";u.style.width=f+25+"px";u.style.height=n+25+"px";u.innerHTML="<div style='position: relative'></div>";u.onmouseout=function(z){z.cancelBubble=true;z.stopPropagation&&z.stopPropagation();try{var s=u.firstChild.childNodes;for(z=0;z<s.length;z++)s[z].style.zIndex=
s.length-z}catch(r){}};this._eventLayer.appendChild(u);var G=this,M=function(){try{for(var z=parseInt(this.getAttribute("index")),s=u.firstChild.childNodes,r=0;r<s.length;r++)s[r].style.zIndex=r==z?s.length:s.length-r}catch(D){}};k=function(z){var s=p[z],r=a[z],D=r.getProperty("tooltip")||r.getText(),K=G._paintEventLabel({tooltip:D},{text:s.text},t+s.labelLeft,J+s.top,s.labelSize.width,s.labelSize.height,c);K.elmt.setAttribute("index",z);K.elmt.onmouseover=M;var I=SimileAjax.Graphics.createTranslucentImage(s.iconData.url);
D=G._timeline.getDocument().createElement("div");D.className="timeline-event-icon";D.style.left=s.iconLeft+"px";D.style.top=s.top+"px";D.style.zIndex=p.length-z;D.appendChild(I);D.setAttribute("index",z);D.onmouseover=M;u.firstChild.appendChild(D);z=function(R,L){return G._onClickInstantEvent(K.elmt,L,r)};SimileAjax.DOM.registerEvent(D,"mousedown",z);SimileAjax.DOM.registerEvent(K.elmt,"mousedown",z);G._eventIdToElmt[r.getID()]=D};for(l=0;l<p.length;l++)k(l)};
Timeline.CompactEventPainter.prototype.paintImpreciseInstantEvent=function(a,b,c,d){var e={tooltip:a.getProperty("tooltip")||a.getText()},f={start:a.getStart(),end:a.getEnd(),latestStart:a.getLatestStart(),earliestEnd:a.getEarliestEnd(),isInstant:true},g={url:a.getIcon()};if(g.url==null)g=null;else{g.width=a.getProperty("iconWidth")||b.customIconWidth;g.height=a.getProperty("iconHeight")||b.customIconHeight}var k={text:a.getText(),color:a.getTextColor()||a.getColor(),className:a.getClassName()},j=
this.paintTapeIconLabel(a.getStart(),e,f,g,k,b,c,d),n=this;b=g!=null?function(p,l){return n._onClickInstantEvent(j.iconElmtData.elmt,l,a)}:function(p,l){return n._onClickInstantEvent(j.labelElmtData.elmt,l,a)};SimileAjax.DOM.registerEvent(j.labelElmtData.elmt,"mousedown",b);SimileAjax.DOM.registerEvent(j.impreciseTapeElmtData.elmt,"mousedown",b);if(g!=null){SimileAjax.DOM.registerEvent(j.iconElmtData.elmt,"mousedown",b);this._eventIdToElmt[a.getID()]=j.iconElmtData.elmt}else this._eventIdToElmt[a.getID()]=
j.labelElmtData.elmt};
Timeline.CompactEventPainter.prototype.paintPreciseDurationEvent=function(a,b,c,d){var e={tooltip:a.getProperty("tooltip")||a.getText()},f={start:a.getStart(),end:a.getEnd(),isInstant:false},g={url:a.getIcon()};if(g.url==null)g=null;else{g.width=a.getProperty("iconWidth")||b.customIconWidth;g.height=a.getProperty("iconHeight")||b.customIconHeight}var k={text:a.getText(),color:a.getTextColor()||a.getColor(),className:a.getClassName()},j=this.paintTapeIconLabel(a.getLatestStart(),e,f,g,k,b,c,d),n=this;
b=g!=null?function(p,l){return n._onClickInstantEvent(j.iconElmtData.elmt,l,a)}:function(p,l){return n._onClickInstantEvent(j.labelElmtData.elmt,l,a)};SimileAjax.DOM.registerEvent(j.labelElmtData.elmt,"mousedown",b);SimileAjax.DOM.registerEvent(j.tapeElmtData.elmt,"mousedown",b);if(g!=null){SimileAjax.DOM.registerEvent(j.iconElmtData.elmt,"mousedown",b);this._eventIdToElmt[a.getID()]=j.iconElmtData.elmt}else this._eventIdToElmt[a.getID()]=j.labelElmtData.elmt};
Timeline.CompactEventPainter.prototype.paintImpreciseDurationEvent=function(a,b,c,d){var e={tooltip:a.getProperty("tooltip")||a.getText()},f={start:a.getStart(),end:a.getEnd(),latestStart:a.getLatestStart(),earliestEnd:a.getEarliestEnd(),isInstant:false},g={url:a.getIcon()};if(g.url==null)g=null;else{g.width=a.getProperty("iconWidth")||b.customIconWidth;g.height=a.getProperty("iconHeight")||b.customIconHeight}var k={text:a.getText(),color:a.getTextColor()||a.getColor(),className:a.getClassName()},
j=this.paintTapeIconLabel(a.getLatestStart(),e,f,g,k,b,c,d),n=this;b=g!=null?function(p,l){return n._onClickInstantEvent(j.iconElmtData.elmt,l,a)}:function(p,l){return n._onClickInstantEvent(j.labelElmtData.elmt,l,a)};SimileAjax.DOM.registerEvent(j.labelElmtData.elmt,"mousedown",b);SimileAjax.DOM.registerEvent(j.tapeElmtData.elmt,"mousedown",b);if(g!=null){SimileAjax.DOM.registerEvent(j.iconElmtData.elmt,"mousedown",b);this._eventIdToElmt[a.getID()]=j.iconElmtData.elmt}else this._eventIdToElmt[a.getID()]=
j.labelElmtData.elmt};
Timeline.CompactEventPainter.prototype.paintTapeIconLabel=function(a,b,c,d,e,f,g){var k=this._band,j=function(G){return Math.round(k.dateToPixelOffset(G))};a=j(a);var n=[],p=0,l=0,y=0;if(c!=null){p=f.tapeHeight+f.tapeBottomMargin;l=Math.ceil(f.tapeHeight/f.trackHeight);for(var v=j(c.end)-a,F=j(c.start)-a,t=0;t<l;t++)n.push({start:F,end:v});y=f.trackHeight-p%f.tapeHeight}F=v=0;if(d!=null){if("iconAlign"in d&&d.iconAlign=="center")v=-Math.floor(d.width/2);F=v+d.width+f.iconLabelGap;if(l>0)n[l-1].end=
Math.max(n[l-1].end,F);for(t=d.height+f.iconBottomMargin+y;t>0;){n.push({start:v,end:F});t-=f.trackHeight}}t=this._frc.computeSize(e.text);y=t.height+f.labelBottomMargin+y;var J=F+t.width+f.labelRightMargin;if(l>0)n[l-1].end=Math.max(n[l-1].end,J);for(var u=0;y>0;u++){if(l+u<n.length)n[l+u].end=J;else n.push({start:0,end:J});y-=f.trackHeight}n=this._fitTracks(a,n)*f.trackHeight+f.trackOffset;l={};l.labelElmtData=this._paintEventLabel(b,e,a+F,n+p,t.width,t.height,g);if(c!=null){if("latestStart"in c||
"earliestEnd"in c)l.impreciseTapeElmtData=this._paintEventTape(b,c,f.tapeHeight,n,j(c.start),j(c.end),g.event.duration.impreciseColor,g.event.duration.impreciseOpacity,f,g);if(!c.isInstant&&"start"in c&&"end"in c)l.tapeElmtData=this._paintEventTape(b,c,f.tapeHeight,n,a,j("earliestEnd"in c?c.earliestEnd:c.end),c.color,100,f,g)}if(d!=null)l.iconElmtData=this._paintEventIcon(b,d,n+p,a+v,f,g);return l};
Timeline.CompactEventPainter.prototype._fitTracks=function(a,b){var c;for(c=0;c<this._tracks.length;c++){for(var d=true,e=0;e<b.length&&c+e<this._tracks.length;e++)if(a+b[e].start<this._tracks[c+e]){d=false;break}if(d)break}for(d=0;d<b.length;d++)this._tracks[c+d]=a+b[d].end;return c};
Timeline.CompactEventPainter.prototype._paintEventIcon=function(a,b,c,d,e){b=SimileAjax.Graphics.createTranslucentImage(b.url);var f=this._timeline.getDocument().createElement("div");f.className="timeline-event-icon";f.style.left=d+"px";f.style.top=c+"px";f.appendChild(b);if("tooltip"in a&&typeof a.tooltip=="string")f.title=a.tooltip;this._eventLayer.appendChild(f);return{left:d,top:c,width:e.iconWidth,height:e.iconHeight,elmt:f}};
Timeline.CompactEventPainter.prototype._paintEventLabel=function(a,b,c,d,e,f){var g=this._timeline.getDocument().createElement("div");g.className="timeline-event-label tinytext";g.style.left=c+"px";g.style.width=e+1+"px";g.style.top=d+"px";g.innerHTML=b.text;if("tooltip"in a&&typeof a.tooltip=="string")g.title=a.tooltip;if("color"in b&&typeof b.color=="string")g.style.color=b.color;if("className"in b&&typeof b.className=="string")g.className+=" "+b.className;this._eventLayer.appendChild(g);return{left:c,
top:d,width:e,height:f,elmt:g}};
Timeline.CompactEventPainter.prototype._paintEventTape=function(a,b,c,d,e,f,g,k){f-=e;var j=this._timeline.getDocument().createElement("div");j.className="timeline-event-tape";j.style.left=e+"px";j.style.top=d+"px";j.style.width=f+"px";j.style.height=c+"px";if("tooltip"in a&&typeof a.tooltip=="string")j.title=a.tooltip;if(g!=null&&typeof b.color=="string")j.style.backgroundColor=g;if("backgroundImage"in b&&typeof b.backgroundImage=="string"){j.style.backgroundImage="url("+backgroundImage+")";j.style.backgroundRepeat=
"backgroundRepeat"in b&&typeof b.backgroundRepeat=="string"?b.backgroundRepeat:"repeat"}SimileAjax.Graphics.setOpacity(j,k);if("className"in b&&typeof b.className=="string")j.className+=" "+b.className;this._eventLayer.appendChild(j);return{left:e,top:d,width:f,height:c,elmt:j}};
Timeline.CompactEventPainter.prototype._createHighlightDiv=function(a,b){if(a>=0){var c=this._timeline.getDocument().createElement("div");c.style.position="absolute";c.style.overflow="hidden";c.style.left=b.left-2+"px";c.style.width=b.width+4+"px";c.style.top=b.top-2+"px";c.style.height=b.height+4+"px";this._highlightLayer.appendChild(c)}};
Timeline.CompactEventPainter.prototype._onClickCompositePreciseInstantEvent=function(a,b,c){var d=SimileAjax.DOM.getPageCoordinates(a);this._showBubble(d.left+Math.ceil(a.offsetWidth/2),d.top+Math.ceil(a.offsetHeight/2),c);a=[];for(d=0;d<c.length;d++)a.push(c[d].getID());this._fireOnSelect(a);b.cancelBubble=true;SimileAjax.DOM.cancelEvent(b);return false};
Timeline.CompactEventPainter.prototype._onClickInstantEvent=function(a,b,c){var d=SimileAjax.DOM.getPageCoordinates(a);this._showBubble(d.left+Math.ceil(a.offsetWidth/2),d.top+Math.ceil(a.offsetHeight/2),[c]);this._fireOnSelect([c.getID()]);b.cancelBubble=true;SimileAjax.DOM.cancelEvent(b);return false};
Timeline.CompactEventPainter.prototype._onClickDurationEvent=function(a,b,c){if("pageX"in b){a=b.pageX;var d=b.pageY}else{d=SimileAjax.DOM.getPageCoordinates(a);a=b.offsetX+d.left;d=b.offsetY+d.top}this._showBubble(a,d,[c]);this._fireOnSelect([c.getID()]);b.cancelBubble=true;SimileAjax.DOM.cancelEvent(b);return false};
Timeline.CompactEventPainter.prototype.showBubble=function(a){var b=this._eventIdToElmt[a.getID()];if(b){var c=SimileAjax.DOM.getPageCoordinates(b);this._showBubble(c.left+b.offsetWidth/2,c.top+b.offsetHeight/2,[a])}};
Timeline.CompactEventPainter.prototype._showBubble=function(a,b,c){var d=document.createElement("div");c="fillInfoBubble"in c?[c]:c;for(var e=0;e<c.length;e++){var f=document.createElement("div");d.appendChild(f);c[e].fillInfoBubble(f,this._params.theme,this._band.getLabeller())}SimileAjax.WindowManager.cancelPopups();SimileAjax.Graphics.createBubbleForContentAndPoint(d,a,b,this._params.theme.event.bubble.width)};Timeline.CompactEventPainter.prototype._fireOnSelect=function(a){for(var b=0;b<this._onSelectListeners.length;b++)this._onSelectListeners[b](a)};function UProgressBar(a){this.elid=a.elid;this.id="upb"+Math.ceil(Math.random()*1E8);this.created=false;this.minValue=a.min?a.min:0;this.maxValue=a.max?a.max:0;this.value=a.value?a.value:0}UProgressBar.prototype.setValue=function(a){log("setting value to "+a+" MaxValue is "+this.maxValue);this.value=a;this.paint();this.value==this.maxValue&&this.hide()};
UProgressBar.prototype.paint=function(){log("painting");if(!this.created){var a=document.createElement("div");a.setAttribute("class","progressbar");a.setAttribute("id",this.id+"progressbar");var b=document.createElement("div");b.setAttribute("class","progress");b.setAttribute("id",this.id+"progress");a.appendChild(b);document.getElementById(this.elid).appendChild(a);this.created=true}a=[100*this.value/(this.maxValue-this.minValue)]*2;document.getElementById(this.id+"progress").style.width=a+"px";
log("new width = "+a+"px")};UProgressBar.prototype.getMinValue=function(){return this.minVale};UProgressBar.prototype.getMaxValue=function(){return this.maxValue};UProgressBar.prototype.setMaxValue=function(a){this.maxValue=a};UProgressBar.prototype.getCurrentValue=function(){return this.value};UProgressBar.prototype.hide=function(){log("hiding");document.getElementById(this.id+"progressbar").style.display="none";document.getElementById(this.id+"progress").style.width="0px"};
UProgressBar.prototype.initialize=function(){document.getElementById(this.id+"progressbar").style.display="";document.getElementById(this.id+"progress").style.width="0px";this.value=this.minValue};var gviz_word_cumulus={};gviz_word_cumulus.WordCumulus=function(a){this.container_=a};
gviz_word_cumulus.WordCumulus.prototype.draw=function(a,b){this.data_=a;b=b||{};var c={};c.allowScriptAccess="always";c.wmode="transparent";c.id=this.container_.id;for(var d={mode:"tags",distr:"false",tcolor:(b.text_color||"#ff0000").replace("#","0x"),hcolor:(b.hover_text_color||"#000000").replace("#","0x"),speed:b.speed||100},e="<tags>",f=0;f<a.getNumberOfRows();f++){var g=a.getFormattedValue(f,0),k=a.getFormattedValue(f,1);k="123456";var j=4;if(a.getNumberOfColumns()>2)j=a.getFormattedValue(f,2);
e+="<a href='"+k+"' target='_blank' style='font-size:"+String(j)+"pt;'>"+g+"</a>"}e+="</tags>";d.tagcloud=e;swfobject.embedSWF("http://word-cumulus-goog-vis.googlecode.com/svn/trunk/tagcloud.swf",this.container_.id,b.width||400,b.height||300,"10","",d,{},c)};var swfobject=function(){function a(){if(S.readyState=="complete"){S.parentNode.removeChild(S);b()}}function b(){if(!U){if(q.ie&&q.win){var h=r.createElement("span");try{var i=r.getElementsByTagName("body")[0].appendChild(h);i.parentNode.removeChild(i)}catch(m){return}}U=true;if(V){clearInterval(V);V=null}h=K.length;for(i=0;i<h;i++)K[i]()}}function c(h){if(U)h();else K[K.length]=h}function d(h){if(typeof s.addEventListener!=u)s.addEventListener("load",h,false);else if(typeof r.addEventListener!=u)r.addEventListener("load",
h,false);else if(typeof s.attachEvent!=u)y(s,"onload",h);else if(typeof s.onload=="function"){var i=s.onload;s.onload=function(){i();h()}}else s.onload=h}function e(){for(var h=I.length,i=0;i<h;i++){var m=I[i].id;if(q.pv[0]>0){var o=l(m);if(o){I[i].width=o.getAttribute("width")?o.getAttribute("width"):"0";I[i].height=o.getAttribute("height")?o.getAttribute("height"):"0";if(v(I[i].swfVersion)){if(q.webkit&&q.webkit<312){var w=o.getElementsByTagName(G)[0];if(w){var B=r.createElement("embed"),x=w.attributes;
if(x)for(var A=x.length,C=0;C<A;C++)x[C].nodeName=="DATA"?B.setAttribute("src",x[C].nodeValue):B.setAttribute(x[C].nodeName,x[C].nodeValue);if(w=w.childNodes){x=w.length;for(A=0;A<x;A++)w[A].nodeType==1&&w[A].nodeName=="PARAM"&&B.setAttribute(w[A].getAttribute("name"),w[A].getAttribute("value"))}o.parentNode.replaceChild(B,o)}}t(m,true)}else I[i].expressInstall&&!N&&v("6.0.65")&&(q.win||q.mac)?f(I[i]):g(o)}}else t(m,true)}}function f(h){N=true;var i=l(h.id);if(i){if(h.altContentId){var m=l(h.altContentId);
if(m){O=m;W=h.altContentId}}else O=k(i);if(!/%$/.test(h.width)&&parseInt(h.width,10)<310)h.width="310";if(!/%$/.test(h.height)&&parseInt(h.height,10)<137)h.height="137";r.title=r.title.slice(0,47)+" - Flash Player Installation";m="MMredirectURL="+s.location+"&MMplayerType="+(q.ie&&q.win?"ActiveX":"PlugIn")+"&MMdoctitle="+r.title;var o=h.id;if(q.ie&&q.win&&i.readyState!=4){var w=r.createElement("div");o+="SWFObjectNew";w.setAttribute("id",o);i.parentNode.insertBefore(w,i);i.style.display="none";y(s,
"onload",function(){i.parentNode.removeChild(i)})}j({data:h.expressInstall,id:z,width:h.width,height:h.height},{flashvars:m},o)}}function g(h){if(q.ie&&q.win&&h.readyState!=4){var i=r.createElement("div");h.parentNode.insertBefore(i,h);i.parentNode.replaceChild(k(h),i);h.style.display="none";y(s,"onload",function(){h.parentNode.removeChild(h)})}else h.parentNode.replaceChild(k(h),h)}function k(h){var i=r.createElement("div");if(q.win&&q.ie)i.innerHTML=h.innerHTML;else if(h=h.getElementsByTagName(G)[0])if(h=
h.childNodes)for(var m=h.length,o=0;o<m;o++)!(h[o].nodeType==1&&h[o].nodeName=="PARAM")&&h[o].nodeType!=8&&i.appendChild(h[o].cloneNode(true));return i}function j(h,i,m){var o,w=l(m);if(w){if(typeof h.id==u)h.id=m;if(q.ie&&q.win){var B="",x;for(x in h)if(h[x]!=Object.prototype[x])if(x.toLowerCase()=="data")i.movie=h[x];else if(x.toLowerCase()=="styleclass")B+=' class="'+h[x]+'"';else if(x.toLowerCase()!="classid")B+=" "+x+'="'+h[x]+'"';x="";for(var A in i)if(i[A]!=Object.prototype[A])x+='<param name="'+
A+'" value="'+i[A]+'" />';w.outerHTML='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+B+">"+x+"</object>";R[R.length]=h.id;o=l(h.id)}else if(q.webkit&&q.webkit<312){B=r.createElement("embed");B.setAttribute("type",M);for(var C in h)if(h[C]!=Object.prototype[C])if(C.toLowerCase()=="data")B.setAttribute("src",h[C]);else if(C.toLowerCase()=="styleclass")B.setAttribute("class",h[C]);else C.toLowerCase()!="classid"&&B.setAttribute(C,h[C]);for(var E in i)i[E]!=Object.prototype[E]&&E.toLowerCase()!=
"movie"&&B.setAttribute(E,i[E]);w.parentNode.replaceChild(B,w);o=B}else{A=r.createElement(G);A.setAttribute("type",M);for(var H in h)if(h[H]!=Object.prototype[H])if(H.toLowerCase()=="styleclass")A.setAttribute("class",h[H]);else H.toLowerCase()!="classid"&&A.setAttribute(H,h[H]);for(B in i)if(i[B]!=Object.prototype[B]&&B.toLowerCase()!="movie"){h=A;x=B;C=i[B];E=r.createElement("param");E.setAttribute("name",x);E.setAttribute("value",C);h.appendChild(E)}w.parentNode.replaceChild(A,w);o=A}}return o}
function n(h){var i=l(h);if(i&&(i.nodeName=="OBJECT"||i.nodeName=="EMBED"))if(q.ie&&q.win)i.readyState==4?p(h):s.attachEvent("onload",function(){p(h)});else i.parentNode.removeChild(i)}function p(h){if(h=l(h)){for(var i in h)if(typeof h[i]=="function")h[i]=null;h.parentNode.removeChild(h)}}function l(h){var i=null;try{i=r.getElementById(h)}catch(m){}return i}function y(h,i,m){h.attachEvent(i,m);L[L.length]=[h,i,m]}function v(h){var i=q.pv;h=h.split(".");h[0]=parseInt(h[0],10);h[1]=parseInt(h[1],10)||
0;h[2]=parseInt(h[2],10)||0;return i[0]>h[0]||i[0]==h[0]&&i[1]>h[1]||i[0]==h[0]&&i[1]==h[1]&&i[2]>=h[2]?true:false}function F(h,i){if(!(q.ie&&q.mac)){var m=r.getElementsByTagName("head")[0],o=r.createElement("style");o.setAttribute("type","text/css");o.setAttribute("media","screen");!(q.ie&&q.win)&&typeof r.createTextNode!=u&&o.appendChild(r.createTextNode(h+" {"+i+"}"));m.appendChild(o);if(q.ie&&q.win&&typeof r.styleSheets!=u&&r.styleSheets.length>0){m=r.styleSheets[r.styleSheets.length-1];typeof m.addRule==
G&&m.addRule(h,i)}}}function t(h,i){var m=i?"visible":"hidden";if(U&&l(h))l(h).style.visibility=m;else F("#"+h,"visibility:"+m)}function J(h){return/[\\\"<>\.;]/.exec(h)!=null?encodeURIComponent(h):h}var u="undefined",G="object",M="application/x-shockwave-flash",z="SWFObjectExprInst",s=window,r=document,D=navigator,K=[],I=[],R=[],L=[],S,V=null,O=null,W=null,U=false,N=false,q=function(){var h=typeof r.getElementById!=u&&typeof r.getElementsByTagName!=u&&typeof r.createElement!=u,i=[0,0,0],m=null;if(typeof D.plugins!=
u&&typeof D.plugins["Shockwave Flash"]==G){if((m=D.plugins["Shockwave Flash"].description)&&!(typeof D.mimeTypes!=u&&D.mimeTypes[M]&&!D.mimeTypes[M].enabledPlugin)){m=m.replace(/^.*\s+(\S+\s+\S+$)/,"$1");i[0]=parseInt(m.replace(/^(.*)\..*$/,"$1"),10);i[1]=parseInt(m.replace(/^.*\.(.*)\s.*$/,"$1"),10);i[2]=/r/.test(m)?parseInt(m.replace(/^.*r(.*)$/,"$1"),10):0}}else if(typeof s.ActiveXObject!=u){var o=null,w=false;try{o=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(B){try{o=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");
i=[6,0,21];o.AllowScriptAccess="always"}catch(x){if(i[0]==6)w=true}if(!w)try{o=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(A){}}if(!w&&o)try{if(m=o.GetVariable("$version")){m=m.split(" ")[1].split(",");i=[parseInt(m[0],10),parseInt(m[1],10),parseInt(m[2],10)]}}catch(C){}}w=D.userAgent.toLowerCase();var E=D.platform.toLowerCase();m=/webkit/.test(w)?parseFloat(w.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):false;o=E?/win/.test(E):/win/.test(w);w=E?/mac/.test(E):/mac/.test(w);return{w3cdom:h,
pv:i,webkit:m,ie:false,win:o,mac:w}}();(function(){if(q.w3cdom){c(e);if(q.ie&&q.win)try{r.write("<script id=__ie_ondomload defer=true src=//:><\/script>");(S=l("__ie_ondomload"))&&y(S,"onreadystatechange",a)}catch(h){}if(q.webkit&&typeof r.readyState!=u)V=setInterval(function(){/loaded|complete/.test(r.readyState)&&b()},10);typeof r.addEventListener!=u&&r.addEventListener("DOMContentLoaded",b,null);d(b)}})();(function(){q.ie&&q.win&&window.attachEvent("onunload",function(){for(var h=L.length,i=0;i<
h;i++)L[i][0].detachEvent(L[i][1],L[i][2]);h=R.length;for(i=0;i<h;i++)n(R[i]);for(var m in q)q[m]=null;q=null;for(var o in swfobject)swfobject[o]=null;swfobject=null})})();return{registerObject:function(h,i,m){if(!(!q.w3cdom||!h||!i)){var o={};o.id=h;o.swfVersion=i;o.expressInstall=m?m:false;I[I.length]=o;t(h,false)}},getObjectById:function(h){var i=null;if(q.w3cdom)if(h=l(h)){var m=h.getElementsByTagName(G)[0];if(!m||m&&typeof h.SetVariable!=u)i=h;else if(typeof m.SetVariable!=u)i=m}return i},embedSWF:function(h,
i,m,o,w,B,x,A,C){if(!(!q.w3cdom||!h||!i||!m||!o||!w)){m+="";o+="";if(v(w)){t(i,false);var E={};if(C&&typeof C===G)for(var H in C)if(C[H]!=Object.prototype[H])E[H]=C[H];E.data=h;E.width=m;E.height=o;var T={};if(A&&typeof A===G)for(var X in A)if(A[X]!=Object.prototype[X])T[X]=A[X];if(x&&typeof x===G)for(var P in x)if(x[P]!=Object.prototype[P])if(typeof T.flashvars!=u)T.flashvars+="&"+P+"="+x[P];else T.flashvars=P+"="+x[P];c(function(){j(E,T,i);E.id==i&&t(i,true)})}else if(B&&!N&&v("6.0.65")&&(q.win||
q.mac)){N=true;t(i,false);c(function(){var Q={};Q.id=Q.altContentId=i;Q.width=m;Q.height=o;Q.expressInstall=B;f(Q)})}}},getFlashPlayerVersion:function(){return{major:q.pv[0],minor:q.pv[1],release:q.pv[2]}},hasFlashPlayerVersion:v,createSWF:function(h,i,m){if(q.w3cdom)return j(h,i,m)},removeSWF:function(h){q.w3cdom&&n(h)},createCSS:function(h,i){q.w3cdom&&F(h,i)},addDomLoadEvent:c,addLoadEvent:d,getQueryParamValue:function(h){var i=r.location.search||r.location.hash;if(h==null)return J(i);if(i){i=
i.substring(1).split("&");for(var m=0;m<i.length;m++)if(i[m].substring(0,i[m].indexOf("="))==h)return J(i[m].substring(i[m].indexOf("=")+1))}return""},expressInstallCallback:function(){if(N&&O){var h=l(z);if(h){h.parentNode.replaceChild(O,h);if(W){t(W,true);if(q.ie&&q.win)O.style.display="block"}W=O=null;N=false}}}}}();var DEBUG=false,userLoggedIn=false,loggedInUserId,userAccessToken,friends={},likes={},albumInfo={},photosInfo={},locationInfo={},geocodeInfo={},birthdayInfo={},pictureInfo={},genderInfo={},mutualFriends={},mutualLikes={},educationInfo={},activityData={},MONTHS=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],map,infowindow,geocoder=new google.maps.Geocoder,lat_min=90,lat_max=-90,lng_min=180,lng_max=-180,FeedLoadComplete=true,OFFSETCOUNT=50,AlbumsLoaded=false,activityloadcount=
0,albumsLoading=false,progressbarobj=new UProgressBar({elid:"waiting",min:0,max:0,value:0}),revealAlbumInfo=function(a){log("Started loading album information");a||(a="/albums?ids="+constructCsv(friends)+"&fields=id,name,count,link");FB.api(a,{limit:50},function(b){if(b.error)AlbumsLoaded=true;else{var c="";constructCsv(friends);for(var d in b)if(b.hasOwnProperty(d)){var e=b[d].data;if(b[d].paging)c=b[d].paging.next;var f=0,g=0;if(e&&e.length){f=e.length;for(var k in e)if(e.hasOwnProperty(k)){var j=
e[k].count?parseInt(e[k].count):0;g+=j}}albumInfo[d]=(albumInfo[d]?parseInt(albumInfo[d]):0)+f;photosInfo[d]=(photosInfo[d]?parseInt(photosInfo[d]):0)+g;if(!userAccessToken){e=c;e=e.substring(e.indexOf("access_token")+13);userAccessToken=e=e.substring(0,e.indexOf("&")==-1?e.length:e.indexOf("&"))}}AlbumsLoaded=true;log("Completed loading album information")}})};
function getAlbumsForDropdown(){var a=document.getElementById("friendsalbumselect").value;if(!a||a==""||a=="-1")a="me";getAlbumsForUser(a)}
var getAlbumsForUser=function(a,b){if(!albumsLoading){albumsLoading=true;var c="<br><br>Loading "+friends[a]+"&apos;s Albums<br><br>";document.getElementById("album_detail").innerHTML=c;b||(b="/"+a+"/albums?fields=id,name,count,link,from,description,created_time,location,comments");FB.api(b,{limit:50},function(d){var e=[""];if(d.error)albumsLoading=false;else{var f="",g=d.data;if(d.paging)f=d.paging.next;if(g&&g.length)for(var k in g)if(g.hasOwnProperty(k)){d=g[k].id;var j=g[k].name,n=g[k].link,p=
g[k].created_time;p=p?p.getDateFromfacebookFormat().getFormattedDate():"";var l=g[k].count,y=g[k].location,v=g[k].description,F=0;if(g[k].comments)F=g[k].comments.data.length;var t=f;t=t.substring(t.indexOf("access_token")+13);t=t.substring(0,t.indexOf("&")==-1?t.length:t.indexOf("&"));e.push('<div class="albumbox"><a href="',n,'" target="new">');e.push('<div class="bold">',j,"</div>");e.push('<div class="albumimage" style="background-image:url(https://graph.facebook.com/',d,"/picture?access_token=",
t,');"></div>');e.push('</a><div class="albumtext"><span>',p,"<br>Photos:",l);y&&e.push("<br>Location: ",y);e.push("<br>Comments: ",F);v&&e.push("<br><br>",v);e.push("</span></div>");e.push("</div>")}c="<br>";if(albumsLoading){document.getElementById("album_detail").innerHTML=c+e.join("");albumsLoading=false}}})}},getPhotosForUser=function(a,b){if(!albumsLoading){albumsLoading=true;var c="<br><br>Loading "+friends[a]+"&apos;s Photos<br><br>";document.getElementById("album_detail").innerHTML=c;b||
(b="/"+a+"/albums?fields=id");FB.api(b,{limit:50},function(d){var e=[""];if(d.error)albumsLoading=false;else{if((d=d.data)&&d.length)for(var f in d)d.hasOwnProperty(f)&&e.push(d[f].id,",");e=e.join("");window.setTimeout('getPhotosForAlbums("'+e.substring(0,e.length-1)+'")',200)}})}},getPhotosForAlbums=function(a){url="/photos?ids="+a+"&fields=id,link,picture,icon,from";FB.api(url,{limit:50},function(b){document.getElementById("album_detail");var c=[""];if(!b.error){var d=b.data,e=0,f;for(f in b)if(b.hasOwnProperty(f)){if((d=
b[f].data)&&d.length)for(var g in d)if(d.hasOwnProperty(g)){c.push('<a href="',d[g].link,'" target="new"><div class="picturebox" style="background-image:url(',d[g].picture,');"></div></a>');e++;if(e>500){c.push('<br><div style="clear:both;color:#999999">(Only 500 photos displayed)</div>');break}}if(e>500)break}htmlText="<br>";document.getElementById("album_detail").innerHTML=htmlText+c.join("")}albumsLoading=false})},displayAlbumInfo=function(){$("#friendsalbumselect").change(getAlbumsForDropdown);
var a="Album and Photo information of all your "+countItems(friends)+" friends on Facebook<br>";a+='<table class="orange"><thead><tr><th>ID</th><th>Name</th><th>Albums</th><th>Photos</th></tr></thead>';var b="odd",c;for(c in albumInfo)if(albumInfo.hasOwnProperty(c)){b=b=="odd"?"":"odd";a+='<tr class="'+b+'"><td><img src="'+pictureInfo[c]+'"></td><td>'+friends[c]+"</td><td>"+albumInfo[c]+"</td><td>"+photosInfo[c]+"</td></tr>"}drawAlbumChart();drawPhotoChart()},displayLocationInfo=function(){var a=
countItems(locationInfo),b=countItems(geocodeInfo);if(b+1!=a){progressbarobj.setMaxValue(a);progressbarobj.setValue(b);log("Still waiting for the address geocoding.. Waiting..");setTimeout("displayLocationInfo()",1E3)}else{dropMarkers();drawLocationTable();log("Drawing map complete")}},displayBirthdayInfo=function(){displayCurrentYear("2011");displayUpcomingBirthdays();drawBirthdayTable()};
function drawAlbumChart(){var a=[],b;for(b in albumInfo)albumInfo.hasOwnProperty(b)&&a.push([b,albumInfo[b]]);a.sort(function(e,f){return f[1]-e[1]});b=[];for(var c=0;c<a.length;c++){if(c==10)break;log("Adding "+friends[a[c][0]]+" and "+a[c][1]+" to the album list");var d=[];d.push(a[c][0]);d.push(a[c][1]);b.push(d)}highalbumoptions.series[0].data=b;new Highcharts.Chart(highalbumoptions)}
function drawPhotoChart(){var a=[],b;for(b in photosInfo)photosInfo.hasOwnProperty(b)&&a.push([b,photosInfo[b]]);a.sort(function(e,f){return f[1]-e[1]});b=[];for(var c=0;c<a.length;c++){if(c==10)break;log("Adding "+friends[a[c][0]]+" and "+a[c][1]+" to the photo list");var d=[];d.push(a[c][0]);d.push(a[c][1]);b.push(d)}highphotooptions.series[0].data=b;new Highcharts.Chart(highphotooptions)}
function drawGenderChart(){var a=[],b;for(b in genderInfo)if(genderInfo.hasOwnProperty(b)){var c=[];c.push(b);c.push(genderInfo[b].length);a.push(c)}highgenderoptions.series[0].data=a;new Highcharts.Chart(highgenderoptions)}function drawEducationChart(){var a=[],b;for(b in educationInfo)if(educationInfo.hasOwnProperty(b)){var c=[];c.push(b);c.push(educationInfo[b].length);a.push(c)}higheducationoptions.series[0].data=a;new Highcharts.Chart(higheducationoptions)}
function initialize(){var a={zoom:8,center:new google.maps.LatLng(17.4,78.6),mapTypeId:google.maps.MapTypeId.ROADMAP};map=new google.maps.Map(document.getElementById("map_canvas"),a);infowindow=new google.maps.InfoWindow;google.maps.event.addListener(map,"click",function(){hideInfoWindow()})}function dropMarkers(){initialize();var a=0,b;for(b in locationInfo)!locationInfo.hasOwnProperty(b)||b=="Unknown"||function(c,d){setTimeout(function(){displayOnMap(c,d)},a++*0)}(b,locationInfo[b])}
var localSearch,localSearchCounter=0,locationArray=[];function localSearchComplete(){if(localSearch.results&&localSearch.results.length>0){var a=new google.maps.LatLng(localSearch.results[0].lat,localSearch.results[0].lng);geocodeInfo[locationArray[localSearchCounter]]=a}else geocodeInfo[locationArray[localSearchCounter]]=null;localSearchCounter++;localSearchNextAddress()}
function convertLocationToArray(){for(var a in locationInfo)!locationInfo.hasOwnProperty(a)||a=="Unknown"||(locationArray[locationArray.length]=a)}function localSearchNextAddress(){if(!(localSearchCounter>=locationArray.length)){var a=locationArray[localSearchCounter];localSearch=new google.search.LocalSearch;localSearch.setSearchCompleteCallback(this,localSearchComplete,null);localSearch.execute(a)}}function geocodeAllAddresses(){convertLocationToArray();localSearchNextAddress()}
function geocodeAddress(a){geocoder.geocode({address:a},function(b,c){if(c==google.maps.GeocoderStatus.OK){geocodeInfo[a]=b[0].geometry.location;log("Geocoded "+a+" to "+b[0].geometry.location.toString())}else geocodeInfo[a]=null})}
function displayOnMap(a,b){var c=geocodeInfo[a];if(c){map.setCenter(c);var d=c.lat(),e=c.lng();if(d<lat_min)lat_min=d;if(d>lat_max)lat_max=d;if(e<lng_min)lng_min=e;if(e>lng_max)lng_max=e;for(d=0;d<b.length;d++){e=new google.maps.Marker({map:map,icon:"faceicon.ico",position:c,animation:google.maps.Animation.DROP,draggable:false,clickable:true});google.maps.event.addListener(e,"click",function(){moreDetail(c,b,a)})}map.fitBounds(new google.maps.LatLngBounds(new google.maps.LatLng(lat_min,lng_min),new google.maps.LatLng(lat_max,
lng_max)))}}function hideInfoWindow(){infowindow.close()}function moreDetail(a,b,c){infowindow.setPosition(a);a="";a+="<b>"+b.length+" friend"+(b.length==1?"":"s")+" in "+c+"</b><br>";for(c=0;c<b.length;c++)a+='<img src="'+pictureInfo[b[c]]+'" title="'+friends[b[c]]+'">&nbsp;';infowindow.setContent(a);infowindow.open(map)}function countItems(a){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b}
function constructCsv(a){var b="",c;for(c in a)if(a.hasOwnProperty(c))b+=c+",";return b.substring(0,b.length-1)}
function displayBirthdays(a,b,c){a=['<div style="width:100%">'];var d=0,e;for(e in birthdayInfo)if(!(e=="Unknown"||!birthdayInfo.hasOwnProperty(e)))if(e==b){var f=birthdayInfo[e];total=0;for(var g in f)if(f.hasOwnProperty(g))if(!(g=="Unknown"||c&&c!=g))for(var k=0;k<f[g].length;k++){d++;a.push('<div class="userbox"><img src="',pictureInfo[f[g][k]],'" align="left">&nbsp;',MONTHS[b-1],"&nbsp;",g,"<br>&nbsp;<b>",friends[f[g][k]],"</b></div>")}}a.push('<div style="clear:both"></div>');a.push("</div>");
b="<br><b>"+(d==0?"No":d)+" friends with birthdays "+(c?"on ":"in ")+MONTH_NAMES[b-1]+" "+(c?c:"")+"</b><br><br>";document.getElementById("calendar_div_detail").innerHTML=b+a.join("")}
function displayUpcomingBirthdays(){var a=0,b=0,c=new Date,d=c.getMonth();c=c.getDate();var e=['<div style="width:350px">'];e.push('<span class="bold"><u>Upcoming birthdays</u>:</span>');if(countItems(birthdayInfo)!=0){var f=d+1;do{var g=birthdayInfo[f],k;for(k in g)if(g.hasOwnProperty(k))if(!(k=="Unknown"||parseInt(k,10)<parseInt(c,10)&&f==d+1)){for(var j=0;j<g[k].length;j++){a++;j==0?e.push("<br><b>",MONTHS[f-1],"&nbsp;",k,"</b>&nbsp;-&nbsp;",friends[g[k][j]]):e.push(",&nbsp;",friends[g[k][j]]);
if(a>5)break}if(a>5)break}if(a>5)break;f++;b++;if(f>12)f=1}while(a<5||b>1)}else e.push("None in the next 2 months");e.push("</div><br>");document.getElementById("upcoming_div_detail").innerHTML=e.join("")}
function displayAllFriends(){var a=[""],b;for(b in pictureInfo)friends[b]?a.push('<div class="userbox"><img src="',pictureInfo[b],'" align="left">&nbsp;<b>',friends[b],"</b></div>"):a.push('<div class="userbox"><img src="',pictureInfo[b],'" align="left">&nbsp;<b>',"You","</b></div>");document.getElementById("friendsBlock").innerHTML+=a.join("")}function initCaps(a){if(a&&a.length>0)a=a.substr(0,1).toUpperCase()+a.substring(1,a.length);return a}
function log(a){if(DEBUG)document.getElementById("debugLog").innerHTML=new Date+" => "+a+"<br>"+document.getElementById("debugLog").innerHTML}function formatData(a){return a}function reloadTimeline(){var a=document.getElementById("friendselect").value;if(!a||a==""||a=="-1")a="me";displayTimeline(a)}function displayTimeline(a){$("#friendselect").change(reloadTimeline);if(FeedLoadComplete){FeedLoadComplete=false;clearTimeline();retrieveFeedInfo(a)}}
var retrieveFeedInfo=function(a,b){log("<br>retrieveFeedInfo with offset : "+b);a||(a="me");var c={};c.limit=OFFSETCOUNT;if(b)c.until=b;url="/"+a+"/feed?fields=id,type,message,likes,comments,from";FB.api(url,c,function(d){if(d.error)FeedLoadComplete=true;else{var e="",f=[];if(d.paging&&d.paging.next){e=d.paging.next;e=e.substring(e.indexOf("until=")+6);if(e.indexOf("&")!=-1)e=e.substring(0,e.indexOf("&"))}if(d.data)if((d=d.data)&&d.length){log(d.length+" posts retrieved");for(var g in d)if(d.hasOwnProperty(g)){var k=
d[g].id,j=k.substring(k.indexOf("_")+1),n=k.substring(0,k.indexOf("_")),p=formatData(d[g].message),l=d[g].created_time,y="Status Update";k=n;if(d[g].from&&d[g].from.id!=n){k=n;n=d[g].from.id;y="Posted by "+d[g].from.name}if(d[g].type!="link"){if(d[g].type=="video")p="(video)";var v=[];if(d[g].comments){p&&p!=""&&v.push({postid:j,user:k,friendid:n,title:y,message:p,createdtime:l});for(var F=d[g].comments.data,t=0;t<F.length;t++){p=F[t];n=p.from.id;(p=p.message)&&p!=""&&v.push({postid:j,user:k,friendid:n,
title:y,message:p,createdtime:l})}v.reverse()}else p&&p!=""&&v.push({postid:j,user:k,friendid:n,title:y,message:p,createdtime:l});f=f.concat(v)}}}f.length>0&&updateTimeline(f);if(e&&e!=""){e=parseInt(e,10)-1;FeedLoadComplete=false;retrieveFeedInfo(k,e)}else FeedLoadComplete=true}})};
function createFriendsDropdown(){var a=[],b;for(b in friends)friends.hasOwnProperty(b)&&a.push([b,friends[b]]);a.sort(function(e,f){var g=e[1],k=f[1];if(g==k)return 0;if(g>k)return 1;if(g<k)return-1});b=document.createElement("select");b.setAttribute("id","friendselect");b.options[b.options.length]=new Option("You","me",true,true);var c=document.createElement("select");c.setAttribute("id","friendsalbumselect");c.options[c.options.length]=new Option("You","me",true,true);for(var d=0;d<a.length;d++){b.options[b.length]=
new Option(a[d][1],a[d][0],false,false);c.options[c.length]=new Option(a[d][1],a[d][0],false,false)}document.getElementById("friendsList").appendChild(b);document.getElementById("friendsAlbumList").appendChild(c)}
function displayFriendSphere(){var a=new google.visualization.DataTable;a.addColumn("string","Name");a.addColumn("string","ID");a.addRows(countItems(friends));var b=0,c;for(c in friends)if(friends.hasOwnProperty(c)){var d=c;a.setCell(b,0,friends[c]);a.setCell(b,1,d);b++}(new gviz_word_cumulus.WordCumulus(document.getElementById("friendsSphere"))).draw(a,{text_color:"#663300",hover_text_color:"#000066",speed:1,width:900,height:600})}
function displayMutualFriendInfo(){var a=document.createElement("script");a.type="text/javascript";a.src="https://api.facebook.com/method/fql.multiquery?queries=%7B'query1'%3A'SELECT%20uid2%20FROM%20friend%20WHERE%20uid1%20%3D%20"+loggedInUserId+"'%2C'query2'%3A'SELECT%20uid1%2C%20uid2%20FROM%20friend%20WHERE%20uid1%20IN%20(SELECT%20uid2%20FROM%20%23query1)%20AND%20uid2%20IN%20(SELECT%20uid2%20FROM%20%23query1)'%7D&access_token="+userAccessToken+"&format=json&callback=foundMutualFriends";a.async=
true;document.getElementById("mutuals").appendChild(a)}function foundMutualFriends(a){mutualFriends={};var b=a[1].fql_result_set;for(a=0;a<b.length;a++){var c=b[a],d=c.uid1;mutualFriends[d]||(mutualFriends[d]=[]);mutualFriends[d][mutualFriends[d].length]=c.uid2}b=[];c=[];for(a in mutualFriends){d=mutualFriends[a];b.push(friends[a]);c.push(d.length)}highfriendoptions.xAxis.categories=b;highfriendoptions.series[0].data=c;new Highcharts.Chart(highfriendoptions)}
function loadLikesInfo(){FB.api("/me/likes",function(a){for(var b=0;b<a.data.length;b++)likes[a.data[b].id]=a.data[b].name})}
function displayMutualLikesInfo(){var a=document.createElement("script");a.type="text/javascript";a.src="https://api.facebook.com/method/fql.query?query=select%20uid%2C%20page_id%2C%20type%20%20from%20page_fan%20where%20page_id%20in%20(select%20page_id%20from%20page_fan%20where%20uid%20%3D%20me())%20and%20uid%20%20in%20(select%20uid2%20from%20friend%20where%20uid1%3Dme())%20&access_token="+userAccessToken+"&format=json&callback=foundMutualLikes";a.async=true;document.getElementById("mutuallikes").appendChild(a)}
function foundMutualLikes(a){mutualLikes={};for(var b=0;b<a.length;b++){var c=a[b],d=c.page_id;mutualLikes[d]||(mutualLikes[d]=[]);mutualLikes[d][mutualLikes[d].length]=c.uid}a=[];c=[];for(b in mutualLikes){d=mutualLikes[b];a.push(likes[b]);c.push(d.length)}highlikeoptions.xAxis.categories=a;highlikeoptions.series[0].data=c;new Highcharts.Chart(highlikeoptions)}String.prototype.getDateFromfacebookFormat=function(){var a=this.split(/[-:T+]/);a[1]-=1;a.pop();return new Date(Date.UTC.apply(Date,a))};
Date.prototype.getFormattedDate=function(){return this.getDate()+" "+MONTHS[this.getMonth()]+" "+this.getFullYear()};Date.prototype.getFormattedDateTime=function(){var a="PM",b=this.getHours();if(b<12)a="AM";if(b==0)b=12;else if(b>12)b-=12;var c=""+this.getMinutes();if(c.length==1)c="0"+c;var d=""+this.getSeconds();if(d.length==1)d="0"+d;return this.getDate()+" "+MONTHS[this.getMonth()]+" "+this.getFullYear()+" "+b+":"+c+":"+d+" "+a};
if(!Array.indexOf)Array.prototype.indexOf=function(a){for(var b=0;b<this.length;b++)if(this[b]==a)return b;return-1};var polltime=30,lastpolltime=0,searchtimer,searchStr,individualtimers=[];$(function(){$("#searchStr").keyup(function(a){var b=document.getElementById("searchStr").value;a.keyCode==13&&b!=""&&searchFacebook()})});
function searchFacebook(){searchStr=document.getElementById("searchStr").value;if(searchStr!=""){searchtimer&&window.clearTimeout(searchtimer);for(var a=0;a<individualtimers.length;a++)individualtimers[a]&&window.clearTimeout(individualtimers[a]);lastpolltime=0;$("#searchResults .item").removeClass("border").html("");continueSearching()}}
function continueSearching(){var a={};a.limit=10;FB.api("/search?q="+searchStr+"&type=post",a,function(b){b.error||displaySearchResults(b.data)});searchtimer=window.setTimeout("continueSearching();",35E3)}function displaySearchResults(a){for(var b=a.length,c=polltime/b,d=0;d<b;d++)individualtimers[d]=window.setTimeout(function(e){return function(){addNewElement(a[b-e-1])}}(d),c*1E3*d)}
function addNewElement(a){var b=a.created_time;b=b.getDateFromfacebookFormat().getTime();if(!(lastpolltime>=b)){if(lastpolltime<b)lastpolltime=b;b=new Date(b);$("#searchResults .item:last").remove();var c='<img src="http://graph.facebook.com/'+a.from.id+'/picture">',d="";if(a.message)d+=a.message;if(a.name)d+="&nbsp;&nbsp;"+a.name;if(a.description)d+="&nbsp;&nbsp;"+a.description;d=d.replace(RegExp(searchStr,"gi"),'<span style="background-color:#FFFBF0;font-weight:bold">'+searchStr+"</span>");c='<table border="0" cellpadding="5" cellspacing="2"><tr><td width="60" align="center">'+
c+'</td><td><a target="_blank" href="http://www.facebook.com/'+a.from.id+"/posts/"+a.id.substring(a.id.indexOf("_")+1)+'"><b>'+a.from.name+"</b></a> &nbsp;:&nbsp;"+d+(a.type=="video"?' <span style="color:#4D2600">[Video]</span>':"")+"<br><br>";if(a.icon)c+='<img src="'+a.icon+'">&nbsp;';c+='<span style="color:#999999">'+b+"</span></td></tr></table>";$("<div>").addClass("item").addClass("border").css("opacity","1").html(c).insertBefore("#searchResults .item:first").hide().fadeIn(1E3)}};function constructPartialCsv(a,b,c){var d="",e=0,f;for(f in a)if(e<b)e++;else if(e>=c)break;else if(a.hasOwnProperty(f)){d+=f+",";e++}return d.substring(0,d.length-1)}
function captureActivityMetrics(){log("Start of captureActivityMetrics");var a=new Date;a=a.setDate(a.getDate()-30);for(var b=countItems(friends),c=0;c<b;){var d=function(e,f){return function(){retrieveActivityInfo(e,parseInt(f/1E3,10))}}(constructPartialCsv(friends,c,c+20),a);activityloadcount++;window.setTimeout(d,c*100);c+=20}refreshActivityChart()}
function refreshActivityChart(){if(activityloadcount==0){displayActivityChart();document.getElementById("activityincompletemsg").innerHTML=""}else window.setTimeout("refreshActivityChart()",1E3)}
function displayActivityChart(){activityoptions.xAxis.categories=[];activityoptions.series[0].data=[];activityoptions.series[1].data=[];activityoptions.series[2].data=[];activityoptions.series[3].data=[];activityoptions.series[4].data=[];for(var a in activityData)if(activityData.hasOwnProperty(a)){activityoptions.xAxis.categories.push(friends[a]);activityoptions.series[0].data.push(activityData[a].V);activityoptions.series[1].data.push(activityData[a].S);activityoptions.series[2].data.push(activityData[a].L);
activityoptions.series[3].data.push(activityData[a].P);activityoptions.series[4].data.push(activityData[a].O)}new Highcharts.Chart(activityoptions)}
var retrieveActivityInfo=function(a,b){log("<br>retrieveActivityInfo with offset : "+b);var c={};c.limit=100;if(b)c.since=b;url="/feed?ids="+a+"&fields=id,type,message,likes,comments,from";FB.api(url,c,function(d){activityloadcount--;if(!d.error){for(var e in d)if(d.hasOwnProperty(e)){var f=d[e].data,g=0,k=0,j=0,n=0,p=0,l;for(l in f)if(f[l].type=="status")g++;else if(f[l].type=="video")k++;else if(f[l].type=="link")j++;else if(f[l].type=="photo")p++;else f[l].type&&n++;if(k!=0||g!=0||j!=0||p!=0||
n!=0){f={};f.V=k;f.S=g;f.L=j;f.P=p;f.O=n;activityData[e]=f}}displayActivityChart()}})},activityoptions={chart:{renderTo:"highactivity",defaultSeriesType:"column"},title:{text:"Profile Activity Chart"},subtitle:{text:"(Whose profile is the most active in the last 30 days?)"},credits:{enabled:false},xAxis:{labels:{enabled:false},categories:[]},yAxis:{min:0,title:{text:"Number of posts"}},tooltip:{formatter:function(){total=this.point.stackTotal==100?"100+":this.point.stackTotal;return"<b>"+this.x+"</b><br/>"+
this.series.name+": "+this.y+"<br/>Total: "+total}},plotOptions:{column:{stacking:"normal"}},series:[{name:"Videos",data:[]},{name:"Status",data:[]},{name:"Links",data:[]},{name:"Photos",data:[]},{name:"Others",data:[]}]};Highcharts.setOptions({colors:["#4572A7","#AA4643","#89A54E","#80699B","#3D96AE","#DB843D","#919400","#92A8CD","#A47D7C","#B5CA92"],credits:{text:"Spectrum on Facebook",href:"http://www.facebook.com/apps/application.php?id=132839880113484&sk=wall"}});
var highlikeoptions={chart:{renderTo:"highlikes"},title:{text:"Mutual Likes"},subtitle:{text:"(How many of your friends like what you like)"},xAxis:{labels:{enabled:false},categories:[]},yAxis:{title:{text:null}},tooltip:{formatter:function(){return"<b>"+this.x+"</b><br>"+this.y+" friends like it too"}},series:[{type:"column",name:"Number of friends"}]},highfriendoptions={chart:{renderTo:"highfriends"},title:{text:"Mutual Friends"},subtitle:{text:"(How many friends do you have in common)"},xAxis:{labels:{enabled:false},
categories:[]},yAxis:{title:{text:null}},tooltip:{formatter:function(){return"<b>"+this.x+"</b><br>"+this.y+" mutual friends"}},series:[{type:"column",name:"Number of friends"}]},highalbumoptions={chart:{renderTo:"highalbums",plotShadow:true},title:{text:"Top 10 friends with most number of albums"},legend:{labelFormatter:function(){return friends[this.name]},layout:"vertical",align:"right",verticalAlign:"top",x:0,y:50,borderWidth:0},tooltip:{formatter:function(){return"<b>"+friends[this.point.name]+
"</b><br>"+this.y+" albums"}},plotOptions:{pie:{allowPointSelect:true,cursor:"pointer",dataLabels:{enabled:false},showInLegend:true,point:{events:{click:function(){getAlbumsForUser(this.name)}}}}},series:[{type:"pie",name:"Number of Albums"}]},highphotooptions={chart:{renderTo:"highphotos",plotShadow:true},title:{text:"Top 10 friends with most number of photos"},legend:{labelFormatter:function(){return friends[this.name]},layout:"vertical",align:"right",verticalAlign:"top",x:0,y:50,borderWidth:0},
tooltip:{formatter:function(){return"<b>"+friends[this.point.name]+"</b><br>"+this.y+" photos"}},plotOptions:{pie:{allowPointSelect:true,cursor:"pointer",dataLabels:{enabled:false},showInLegend:true,point:{events:{click:function(){getPhotosForUser(this.name)}}}}},series:[{type:"pie",name:"Number of Photos"}]},highgenderoptions={chart:{renderTo:"highgender",plotShadow:true},title:{text:"Gender distribution of your friends"},legend:{layout:"vertical",align:"right",verticalAlign:"top",x:0,y:50,borderWidth:0},
tooltip:{formatter:function(){return"<b>"+this.point.name+"</b> : "+this.y}},plotOptions:{pie:{allowPointSelect:true,cursor:"pointer",dataLabels:{enabled:false},showInLegend:true}},series:[{type:"pie",name:"Gender"}]},higheducationoptions={chart:{renderTo:"higheducation",plotShadow:true},title:{text:"Education distribution of your friends"},legend:{layout:"vertical",align:"right",verticalAlign:"top",x:0,y:50,borderWidth:0},tooltip:{formatter:function(){return"<b>"+this.point.name+"</b> : "+this.y}},
plotOptions:{pie:{allowPointSelect:true,cursor:"pointer",dataLabels:{enabled:false},showInLegend:true}},series:[{type:"pie",name:"Education"}]};
